//! Central Tauri command registry.
//!
//! New commands should be registered here so `lib.rs` can keep the builder
//! setup focused on application lifecycle wiring.

use crate::{commands, launcher};

pub fn register_all(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    builder.invoke_handler(tauri::generate_handler![
        // Boot and persistence
        commands::import_legacy::import_legacy_localstorage,
        commands::keyring::set_keyring_fallback_dismissed,
        commands::snapshot::get_initial_app_state,
        commands::persist_connections::persist_connection,
        commands::persist_favorites::persist_favorites,
        commands::persist_mru::persist_mru,
        commands::persist_mru::clear_mru,
        commands::persist_settings::persist_setting,
        commands::persist_settings::reset_setting,
        commands::persist_settings::get_setting,
        commands::persist_favorites::list_favorites,
        commands::persist_workspace::persist_workspace,
        commands::cancel_query::cancel_query_native,
        commands::release_tab_connection::release_tab_connection,
        // Connection management
        commands::connection::crud::list_connections,
        commands::connection::session::get_session_id,
        commands::connection::crud::save_connection,
        commands::connection::crud::delete_connection,
        commands::connection::crud::test_connection,
        commands::connection::sqlite_file::create_sqlite_database_file,
        commands::connection::crud::connect,
        commands::connection::crud::disconnect,
        commands::connection::groups::list_groups,
        commands::connection::groups::save_group,
        commands::connection::groups::delete_group,
        commands::connection::groups::move_connection_to_group,
        commands::connection::io::export_connections,
        commands::connection::io::import_connections,
        commands::connection::io::export_connections_encrypted,
        commands::connection::io::import_connections_encrypted,
        // RDB schema, DDL, and query
        commands::rdb::schema::list_schemas,
        commands::rdb::schema::list_tables,
        commands::rdb::schema::get_table_columns,
        commands::rdb::schema::list_schema_columns,
        commands::rdb::query::query_table_data,
        commands::rdb::query::count_null_rows,
        commands::rdb::schema::get_table_indexes,
        commands::rdb::schema::get_table_constraints,
        commands::rdb::ddl::drop_table,
        commands::rdb::ddl::rename_table,
        commands::rdb::ddl::add_column,
        commands::rdb::ddl::drop_column,
        commands::rdb::ddl::alter_table,
        commands::rdb::ddl::create_table,
        commands::rdb::ddl::create_table_plan,
        commands::rdb::ddl::create_index,
        commands::rdb::ddl::drop_index,
        commands::rdb::ddl::add_constraint,
        commands::rdb::ddl::drop_constraint,
        commands::rdb::ddl::create_trigger,
        commands::rdb::ddl::drop_trigger,
        commands::rdb::schema::list_views,
        commands::rdb::schema::list_functions,
        commands::rdb::schema::get_view_definition,
        commands::rdb::schema::get_view_columns,
        commands::rdb::schema::get_function_source,
        commands::rdb::schema::list_triggers,
        commands::rdb::schema::get_trigger_source,
        commands::rdb::schema::list_postgres_types,
        commands::rdb::query::execute_query,
        commands::rdb::query::execute_query_batch,
        commands::rdb::query::execute_query_dry_run,
        commands::rdb::query::cancel_query,
        commands::file_analytics::duckdb_register_file_analytics_source,
        commands::file_analytics::duckdb_preview_file_analytics_source,
        commands::file_analytics::duckdb_execute_file_analytics_query,
        // Cross-paradigm metadata
        commands::meta::list_databases,
        commands::meta::switch_active_db,
        commands::meta::verify_active_db,
        commands::meta::list_server_activity,
        commands::meta::kill_server_activity,
        commands::rdb::query::explain_rdb_query,
        commands::document::query::explain_mongo_find,
        commands::meta::collection_stats_rdb,
        commands::meta::collection_stats_mongo,
        commands::meta::server_info,
        commands::meta::slow_queries,
        // Mongo browse and query
        commands::document::browse::list_mongo_databases,
        commands::document::browse::list_mongo_collections,
        commands::document::browse::infer_collection_fields,
        commands::document::browse::list_mongo_indexes,
        commands::document::browse::create_mongo_index,
        commands::document::browse::drop_mongo_index,
        commands::document::browse::get_mongo_validator,
        commands::document::browse::set_mongo_validator,
        commands::document::browse::create_collection,
        commands::document::browse::rename_collection,
        commands::document::browse::drop_mongo_database,
        commands::rdb::ddl::create_rdb_database,
        commands::rdb::ddl::drop_rdb_database,
        commands::document::query::find_documents,
        commands::document::query::aggregate_documents,
        commands::document::query::find_one_document,
        commands::document::query::count_documents,
        commands::document::query::estimated_document_count,
        commands::document::query::distinct_documents,
        commands::document::query::run_mongo_command,
        // Mongo mutation and export
        commands::document::mutate::insert_document,
        commands::document::mutate::update_document,
        commands::document::mutate::delete_document,
        commands::document::mutate::delete_many,
        commands::document::mutate::update_many,
        commands::document::mutate::drop_collection,
        commands::document::mutate::insert_many_documents,
        commands::document::mutate::bulk_write_documents,
        commands::export::export_grid_rows,
        commands::export::write_text_file_export,
        commands::export::export_schema_dump,
        // Window commands
        launcher::launcher_show,
        launcher::launcher_hide,
        launcher::launcher_focus,
        launcher::workspace_show,
        launcher::workspace_hide,
        launcher::workspace_focus,
        launcher::workspace_ensure,
        launcher::workspace_close,
        launcher::app_exit,
        commands::open_workspace_window::open_workspace_window,
        // Preferences and app-local state
        commands::datagrid_prefs::set_datagrid_prefs,
        commands::datagrid_prefs::get_datagrid_prefs,
        commands::datagrid_prefs::reset_datagrid_prefs,
        commands::groups_collapsed::set_group_collapsed,
        commands::meta_sentinel::get_meta_sentinel,
        commands::meta_sentinel::set_meta_sentinel,
        commands::history::add_history_entry,
        commands::history::list_history,
        commands::history::get_history_detail,
        commands::history::clear_history,
        commands::sql_parser::parse_sql_backend,
    ])
}
