// PG-native "exotic" type showcase — the types the portable fixture pipeline
// (base.yaml → 9 engines) can't express uniformly across DBMSs. Lives only in
// Postgres, under schema `showcase`, and is seeded as hand-authored SQL rather
// than through the Faker generator: a valid PostGIS-free `point`, an `int4range`
// or a real image `bytea` is clearer written by hand than probabilistically
// generated.
//
// Each table carries two row groups:
//   1) a handful of curated *edge* rows (all-NULL, empty collections, unbounded
//      ranges, unicode/emoji/RTL, boundary numerics), and
//   2) a `generate_series` bulk fill (default 1000 rows, override with
//      SHOWCASE_ROWS) so the tables have realistic volume for paging/sorting.
//
// Each table is applied as an isolated statement batch: an environment missing
// an optional feature (e.g. libxml for the `xml` column) drops only that one
// table, not the whole gallery.
//
// Idempotent: every block DROPs before CREATE, so it is safe to re-run on each
// `fixtures:load` / `db:reset`.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Client } from "pg";

// Tiny 40px JPEG thumbnails (picsum.photos), committed as base64 so seeding
// needs no network. Regenerate with:
//   curl -sL https://picsum.photos/seed/<name>/40.jpg | base64
// Resolved from cwd (repo root) to match spec.ts's FIXTURES_DIR convention;
// the fixture CLI and vitest both run from the repo root.
const BLOBS = JSON.parse(
  readFileSync(
    resolve(process.cwd(), "scripts/fixtures/showcase-blobs.json"),
    "utf8",
  ),
) as Record<string, string>;

// Bulk row count per showcase table. Env override keeps the "pass it in" knob
// consistent with the rest of the fixture CLI.
const BULK_ROWS = Math.max(0, Number(process.env.SHOWCASE_ROWS ?? 1000));

interface ShowcaseBlock {
  name: string;
  sql: string;
}

/**
 * Prelude — schema + optional-contrib extensions + the native enum type.
 * `setseed` makes the random()-driven bulk fill reproducible within a run.
 * Kept separate so its failure is reported distinctly from a table's.
 */
export const PRELUDE = `
CREATE SCHEMA IF NOT EXISTS showcase;
CREATE EXTENSION IF NOT EXISTS hstore;
DO $$ BEGIN
  CREATE TYPE showcase.mood AS ENUM ('happy', 'sad', 'neutral', 'excited');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
-- DOMAIN = a constrained type alias (closest PG analogue to a SYNONYM/alias).
DO $$ BEGIN
  CREATE DOMAIN showcase.us_zip AS text CHECK (VALUE ~ '^[0-9]{5}$');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
-- Composite type — a user-defined row type.
DO $$ BEGIN
  CREATE TYPE showcase.money_amount AS (amount numeric, currency text);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
SELECT setseed(0.42);
`;

export function buildBlocks(n: number = BULK_ROWS): ShowcaseBlock[] {
  return [
    {
      // bytea (real JPEG) + generated bytea checksum + generated byte size.
      name: "media_assets",
      sql: `
DROP TABLE IF EXISTS showcase.media_assets CASCADE;
CREATE TABLE showcase.media_assets (
  id        serial PRIMARY KEY,
  label     text NOT NULL,
  mime      text,
  width     int,
  height    int,
  bytes     bytea,
  byte_size int   GENERATED ALWAYS AS (octet_length(bytes)) STORED,
  md5sum    bytea GENERATED ALWAYS AS (decode(md5(bytes), 'hex')) STORED
);
INSERT INTO showcase.media_assets (label, mime, width, height, bytes) VALUES
  ('picsum-alpha',   'image/jpeg', 40, 40, decode('${BLOBS.alpha}', 'base64')),
  ('picsum-bravo',   'image/jpeg', 40, 40, decode('${BLOBS.bravo}', 'base64')),
  ('picsum-charlie', 'image/jpeg', 40, 40, decode('${BLOBS.charlie}', 'base64')),
  ('edge-empty-blob','application/octet-stream', 0, 0, '\\x'::bytea),
  ('edge-null-blob', NULL, NULL, NULL, NULL);
INSERT INTO showcase.media_assets (label, mime, width, height, bytes)
SELECT 'asset-' || g, 'application/octet-stream', (g % 512), (g % 512),
       decode(md5(g::text || random()::text), 'hex')
FROM generate_series(1, ${n}) g;
`,
    },
    {
      // geometric (native, no PostGIS) + network types.
      name: "warehouses",
      sql: `
DROP TABLE IF EXISTS showcase.warehouses CASCADE;
CREATE TABLE showcase.warehouses (
  id           serial PRIMARY KEY,
  code         text NOT NULL,
  location     point,
  service_area polygon,
  coverage     box,
  subnet       cidr,
  gateway_mac  macaddr
);
INSERT INTO showcase.warehouses (code, location, service_area, coverage, subnet, gateway_mac) VALUES
  ('SEA-01', '(-122.33,47.61)'::point,
             '((-122.4,47.5),(-122.2,47.5),(-122.2,47.7),(-122.4,47.7))'::polygon,
             '((-122.4,47.5),(-122.2,47.7))'::box, '10.10.0.0/16'::cidr, '08:00:2b:aa:bb:cc'::macaddr),
  ('NYC-02', '(-73.99,40.73)'::point,
             '((-74.02,40.70),(-73.95,40.70),(-73.95,40.78))'::polygon,
             '((-74.02,40.70),(-73.95,40.78))'::box, '2001:db8:abcd::/48'::cidr, '02-42-ac-11-00-05'::macaddr),
  ('edge-nulls', NULL, NULL, NULL, NULL, NULL);
INSERT INTO showcase.warehouses (code, location, service_area, coverage, subnet, gateway_mac)
SELECT 'WH-' || g,
       point(random() * 360 - 180, random() * 180 - 90),
       polygon(box(point(g % 100, g % 100), point(g % 100 + 1, g % 100 + 1))),
       box(point(g % 100, g % 100), point(g % 100 + 1, g % 100 + 1)),
       ('10.' || (g % 255) || '.0.0/16')::cidr,
       ('08:00:2b:00:00:' || lpad(to_hex(g % 256), 2, '0'))::macaddr
FROM generate_series(1, ${n}) g;
`,
    },
    {
      // range types + interval + geometric path.
      name: "shipment_windows",
      sql: `
DROP TABLE IF EXISTS showcase.shipment_windows CASCADE;
CREATE TABLE showcase.shipment_windows (
  id             serial PRIMARY KEY,
  ref            text NOT NULL,
  transit_window tstzrange,
  price_band     numrange,
  qty_tier       int4range,
  sla            interval,
  route          path
);
INSERT INTO showcase.shipment_windows (ref, transit_window, price_band, qty_tier, sla, route) VALUES
  ('SHP-1', tstzrange('2025-01-01 00:00+00', '2025-01-05 00:00+00', '[)'),
            numrange(9.99, 49.99), int4range(1, 10), interval '2 days 06:00:00',
            '[(0,0),(1,1),(2,0)]'::path),
  ('SHP-2-unbounded', tstzrange('2025-06-01 00:00+00', NULL),
            numrange(100, NULL), int4range(50, NULL), interval '-12:00:00',
            '((0,0),(5,5))'::path),
  ('edge-empty', 'empty'::tstzrange, 'empty'::numrange, 'empty'::int4range, interval '0', NULL);
INSERT INTO showcase.shipment_windows (ref, transit_window, price_band, qty_tier, sla, route)
SELECT 'SHP-' || g,
       tstzrange(timestamptz '2025-01-01 00:00+00' + (g || ' hours')::interval,
                 timestamptz '2025-01-01 00:00+00' + ((g + 48) || ' hours')::interval, '[)'),
       numrange((g % 100)::numeric, (g % 100 + 50)::numeric),
       int4range(g % 50, g % 50 + 10),
       ((g % 72) || ' hours')::interval,
       ('[(0,0),(' || (g % 10) || ',' || (g % 10) || ')]')::path
FROM generate_series(1, ${n}) g;
`,
    },
    {
      // money + high-precision numeric + bit strings + float specials.
      name: "pricing",
      sql: `
DROP TABLE IF EXISTS showcase.pricing CASCADE;
CREATE TABLE showcase.pricing (
  id             serial PRIMARY KEY,
  sku            text NOT NULL,
  list_price     money,
  precise_amount numeric(30, 10),
  flags          bit(8),
  var_flags      varbit,
  tax_rate       double precision
);
INSERT INTO showcase.pricing (sku, list_price, precise_amount, flags, var_flags, tax_rate) VALUES
  ('SKU-1',   1299.99::money,               123456789012345.6789012345, B'10100001', B'101',          0.0875),
  ('SKU-MAX', 92233720368547758.07::money,  99999999999999999999.9999999999, B'11111111', B'111111111111', 'Infinity'::double precision),
  ('SKU-NEG', (-49.50)::money,              -0.0000000001, B'00000000', B'0', 'NaN'::double precision),
  ('edge-null', NULL, NULL, NULL, NULL, NULL);
INSERT INTO showcase.pricing (sku, list_price, precise_amount, flags, var_flags, tax_rate)
SELECT 'SKU-' || g,
       ((random() * 1000)::numeric(12, 2))::money,
       (random() * 1000000)::numeric(30, 10),
       (g % 256)::bit(8),
       (g % 65536)::bit(16)::varbit,
       random() * 0.3
FROM generate_series(1, ${n}) g;
`,
    },
    {
      // full-text tsvector + native arrays (text/int/uuid) + jsonb + hstore + enum.
      name: "search_docs",
      sql: `
DROP TABLE IF EXISTS showcase.search_docs CASCADE;
CREATE TABLE showcase.search_docs (
  id          serial PRIMARY KEY,
  title       text NOT NULL,
  body_search tsvector,
  tags        text[],
  scores      int[],
  related_ids uuid[],
  facets      jsonb,
  attributes  hstore,
  mood        showcase.mood
);
INSERT INTO showcase.search_docs (title, body_search, tags, scores, related_ids, facets, attributes, mood) VALUES
  ('quick brown fox',
   to_tsvector('english', 'the quick brown fox jumps over the lazy dog'),
   ARRAY['sale','featured','new'], ARRAY[10,20,30],
   ARRAY['11111111-1111-1111-1111-111111111111'::uuid,'22222222-2222-2222-2222-222222222222'::uuid],
   '{"color":"red","in_stock":true,"dims":{"w":10,"h":20}}'::jsonb,
   'brand=>acme, warranty=>2y'::hstore, 'happy'),
  ('unicode 검색 🌟',
   to_tsvector('simple', '한국어 전문 검색 テキスト'),
   ARRAY['한국어','🌟emoji','שלום'], ARRAY[2147483647,-2147483648],
   ARRAY['33333333-3333-3333-3333-333333333333'::uuid],
   '{"emoji":"🌟","nested":{"deep":[true,false,null]}}'::jsonb,
   hstore('greeting','안녕 🌟'), 'excited'),
  ('edge-empty', to_tsvector('simple', ''), ARRAY[]::text[], '{}'::int[], '{}'::uuid[],
   '{}'::jsonb, ''::hstore, 'neutral'),
  ('edge-null', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO showcase.search_docs (title, body_search, tags, scores, related_ids, facets, attributes, mood)
SELECT 'doc-' || g,
       to_tsvector('english', 'document ' || g || ' lorem ipsum dolor sit amet sample text'),
       ARRAY['tag' || (g % 10), 'cat' || (g % 5)],
       ARRAY[g % 100, (g * 3) % 100, (g * 7) % 100],
       ARRAY[gen_random_uuid(), gen_random_uuid()],
       jsonb_build_object('n', g, 'even', (g % 2 = 0), 'grp', g % 5),
       hstore(ARRAY['idx','grp'], ARRAY[g::text, (g % 5)::text]),
       (ARRAY['happy','sad','neutral','excited']::showcase.mood[])[1 + g % 4]
FROM generate_series(1, ${n}) g;
`,
    },
    {
      // network inet (v4/v6) + interval + jsonb + timestamptz + xml.
      name: "access_log",
      sql: `
DROP TABLE IF EXISTS showcase.access_log CASCADE;
CREATE TABLE showcase.access_log (
  id               serial PRIMARY KEY,
  note             text NOT NULL,
  client_ip        inet,
  request_duration interval,
  payload          jsonb,
  occurred_at      timestamptz,
  raw_headers      xml
);
INSERT INTO showcase.access_log (note, client_ip, request_duration, payload, occurred_at, raw_headers) VALUES
  ('ipv4-get', '192.168.1.100'::inet, interval '00:00:01.250',
   '{"method":"GET","path":"/api/x","status":200}'::jsonb, '2025-06-01 12:00:00+00'::timestamptz,
   XML '<headers><h name="ua">curl/8</h></headers>'),
  ('ipv6-post', '2001:db8::dead:beef'::inet, interval '3 days 04:05:06',
   '{"method":"POST","body":{"k":"v"}}'::jsonb, '2025-06-02 08:30:00+09'::timestamptz,
   XML '<headers/>'),
  ('edge-cidr-null', '0.0.0.0/0'::inet, interval '0', 'null'::jsonb, NULL, NULL),
  ('edge-null', NULL, NULL, NULL, NULL, NULL);
INSERT INTO showcase.access_log (note, client_ip, request_duration, payload, occurred_at, raw_headers)
SELECT 'req-' || g,
       ('10.' || (g % 255) || '.' || ((g * 3) % 255) || '.' || ((g * 7) % 255))::inet,
       ((g % 3600) || ' seconds')::interval,
       jsonb_build_object('method', (ARRAY['GET','POST','PUT'])[1 + g % 3],
                          'status', (ARRAY[200,404,500])[1 + g % 3]),
       timestamptz '2025-01-01 00:00+00' + (g || ' minutes')::interval,
       ('<r id="' || g || '"/>')::xml
FROM generate_series(1, ${n}) g;
`,
    },
    {
      // Non-table objects: DOMAIN + composite type usage, VIEW, MATERIALIZED
      // VIEW, FUNCTION, PROCEDURE. Runs last — depends on the tables above,
      // which are already committed by the time this block executes.
      name: "db_objects",
      sql: `
DROP TABLE IF EXISTS showcase.contacts CASCADE;
CREATE TABLE showcase.contacts (
  id      serial PRIMARY KEY,
  name    text NOT NULL,
  zip     showcase.us_zip,       -- DOMAIN (constrained text alias)
  balance showcase.money_amount  -- composite type
);
INSERT INTO showcase.contacts (name, zip, balance) VALUES
  ('Acme',      '90210', ROW(100.50, 'USD')::showcase.money_amount),
  ('Globex',    '10001', ROW(-5.00, 'EUR')::showcase.money_amount),
  ('edge-null', NULL,    NULL);

CREATE OR REPLACE VIEW showcase.expensive_pricing AS
  SELECT id, sku, list_price
  FROM showcase.pricing
  WHERE list_price > 500::money;

DROP MATERIALIZED VIEW IF EXISTS showcase.warehouse_by_subnet;
CREATE MATERIALIZED VIEW showcase.warehouse_by_subnet AS
  SELECT subnet, count(*) AS n
  FROM showcase.warehouses
  WHERE subnet IS NOT NULL
  GROUP BY subnet;

CREATE OR REPLACE FUNCTION showcase.asset_count() RETURNS bigint
  LANGUAGE sql STABLE AS 'SELECT count(*) FROM showcase.media_assets';

CREATE OR REPLACE PROCEDURE showcase.refresh_summary()
  LANGUAGE plpgsql AS $proc$
  BEGIN
    REFRESH MATERIALIZED VIEW showcase.warehouse_by_subnet;
  END;
  $proc$;
`,
    },
  ];
}

/**
 * Apply the PG exotic-type showcase into schema `showcase`. Best-effort per
 * table: a block that fails (e.g. `xml` on a build without libxml) is logged
 * and skipped so the rest of the gallery still lands.
 */
export async function applyPgShowcase(
  c: Client,
  log: (entity: string, count: number, ms: number) => void,
): Promise<void> {
  const preludeStart = Date.now();
  try {
    await c.query(PRELUDE);
  } catch (err) {
    log(
      `showcase.<prelude failed: ${err instanceof Error ? err.message : String(err)}>`,
      0,
      Date.now() - preludeStart,
    );
    return; // schema/enum missing → every table would fail; bail early.
  }

  for (const block of buildBlocks()) {
    const start = Date.now();
    try {
      // Multi-statement batches resolve to an array of results; the bulk
      // INSERT is last, so its rowCount is the meaningful figure to log.
      const res = await c.query(block.sql);
      const rowCount = Array.isArray(res)
        ? (res[res.length - 1]?.rowCount ?? 0)
        : (res.rowCount ?? 0);
      log(`showcase.${block.name}`, rowCount, Date.now() - start);
    } catch (err) {
      log(
        `showcase.${block.name} <skipped: ${err instanceof Error ? err.message : String(err)}>`,
        0,
        Date.now() - start,
      );
    }
  }
}
