// Sprint 401 (2026-05-17) — WASM-backed mongosh statement parser.
//
// 작성 이유: sprint-382/383/384 의 TS 구현 (lexer.ts / parser.ts /
// argList.ts) 을 Rust 로 옮겨 `wasm-pack` 으로 빌드한 모듈을 lazy load
// 하기 위함. 호출부 (`runCommandParser.ts`, `Toolbar.tsx`,
// `useQueryExecution.ts`) 는 *sync* signature 를 기대하므로, 본 facade 는
// 두 모드를 지원한다:
//
//   1. **Eager pre-load** — `src/main.tsx` 가 React mount 직후
//      `void initMongoshWasm()` 을 fire-and-forget. WASM 모듈이 백그라운드
//      에서 로드되는 동안 사용자는 첫 화면을 보고 있다 — 실제 mongosh
//      입력을 시작할 때쯤이면 모듈이 메모리에 있다.
//   2. **Sync surface** — `parseMongoshStatement(sql)` 은 sync 유지.
//      WASM 이 아직 로드 안 됐으면 `unsupported-syntax` 의 "parser
//      initializing" 에러 객체를 반환 — Run 버튼은 disabled 상태로 안전하게
//      대기. 다음 render cycle 에서 WASM 이 로드돼 있으면 실제 결과 반환.
//
// sprint-385 의 SQL facade 와 달리 본 facade 가 sync 인 이유:
// `Toolbar.tsx` 의 `classifyMongoStatement(tab.sql)` 호출이 React render
// function 안에 있다 — 매 keystroke 마다 호출됨. async 로 바꾸면
// `useEffect`/`useState`/debounce pipeline 으로 재구조화해야 하고, 그
// 사이에 Run 버튼의 enable/disable 가 한 프레임씩 늦게 따라가는 race 가
//생긴다. sprint-401 contract `Decision Lock` 에서 본 trade-off 를 명시.

import type {
  MongoshErrorKind,
  MongoshAdminCommand,
  MongoshCollectionCommand,
  MongoshParseError,
  MongoshStatementResult,
} from "./types";

export type {
  MongoshErrorKind,
  MongoshAdminCommand,
  MongoshCollectionCommand,
  MongoshParseError,
  MongoshStatementResult,
};

// ---------------------------------------------------------------------------
// WASM module shape — generated by `wasm-pack build --target web`.
// ---------------------------------------------------------------------------

interface MongoshWasmModule {
  default: (input?: unknown) => Promise<unknown>;
  initSync: (input: { module: BufferSource | WebAssembly.Module }) => unknown;
  parse_mongosh: (input: string) => unknown;
  mongo_completion_vocabulary: () => unknown;
}

let wasmModule: MongoshWasmModule | null = null;
let modulePromise: Promise<MongoshWasmModule> | null = null;

/**
 * Public eager-init entry. Resolves once the WASM linear memory + `parse_
 * mongosh` export are ready. Called once from `src/main.tsx` after React
 * mounts (fire-and-forget) so that `parseMongoshStatement` is sync-ready by
 * the time the user enters a query.
 *
 * Memoized — subsequent calls return the same promise without re-fetching.
 *
 * Optional `precompiledBytes` lets the test-setup pass an on-disk byte
 * buffer; under jsdom the default `fetch()` codepath would fail.
 */
export function initMongoshWasm(
  precompiledBytes?: BufferSource | WebAssembly.Module,
): Promise<void> {
  if (modulePromise === null) {
    modulePromise = (async () => {
      // Dynamic import — Vite tree-splits this into its own chunk so the
      // WASM glue does not land in the main entry bundle.
      // Relative path goes one level up because this file is at
      // `src/lib/mongo/mongoshAst/index.ts` and the wasm-pack output
      // dir is `src/lib/mongo/wasm/` — sibling of the `mongoshAst/`
      // directory, not of this file.
      const mod =
        (await import("../wasm/mongosh_parser_core.js")) as unknown as MongoshWasmModule;
      if (precompiledBytes !== undefined) {
        // Synchronous instantiation against bytes we already have — used
        // by vitest where `fetch()` is not available.
        mod.initSync({ module: precompiledBytes });
      } else {
        // `default` is the init function generated by wasm-pack `--target
        // web`. Calling it with no args lets the glue locate the sibling
        // `.wasm` via `new URL("...", import.meta.url)`.
        await mod.default();
      }
      wasmModule = mod;
      return mod;
    })();
  }
  return modulePromise.then(() => undefined);
}

/**
 * Public entry — parse one mongosh statement and classify it.
 *
 * Sync surface (see file header). If WASM is not yet loaded, returns a
 * synthetic `unsupported-syntax` error so callers keep their narrow-able
 * `MongoshStatementResult` discriminant — no exception flow.
 */
export function parseMongoshStatement(input: string): MongoshStatementResult {
  if (typeof input !== "string") {
    return {
      kind: "error",
      errorKind: "unsupported-syntax",
      message: "expected a string expression",
    };
  }
  if (wasmModule === null) {
    // Cold-boot path. The boot wiring in `main.tsx` fires
    // `initMongoshWasm()` before any QueryTab can render, so in practice
    // users never see this — but we surface a typed error rather than
    // throwing so any pathological caller still narrows cleanly.
    return {
      kind: "error",
      errorKind: "unsupported-syntax",
      message:
        "mongosh parser is initializing — try again in a moment (this should be invisible to end users)",
    };
  }
  const raw = wasmModule.parse_mongosh(input);
  if (!isMongoshStatementResult(raw)) {
    // `serde_wasm_bindgen::to_value` fall-back path. Shouldn't be reachable
    // for any user input — surface as a synthetic error.
    return {
      kind: "error",
      errorKind: "unsupported-syntax",
      message: "internal: WASM bridge returned non-serializable result",
    };
  }
  return raw;
}

export interface MongoshCompletionVocabulary {
  queryOperators: readonly string[];
  projectionOperators: readonly string[];
  updateOperators: readonly string[];
  aggregateStages: readonly string[];
  accumulators: readonly string[];
  expressionOperators: readonly string[];
  typeTags: readonly string[];
  allOperators: readonly string[];
  mongoshCollectionMethods: readonly string[];
  mongoshDbMethods: readonly string[];
  mongoAdminCommands: readonly string[];
}

const MONGOSH_VOCABULARY_GROUP_SEPARATOR = "\u001f";

export function getMongoshCompletionVocabulary(): MongoshCompletionVocabulary | null {
  if (wasmModule === null) return null;
  const raw = wasmModule.mongo_completion_vocabulary();
  return parseMongoshCompletionVocabulary(raw);
}

// ---------------------------------------------------------------------------
// Runtime guards + test escape hatch.
// ---------------------------------------------------------------------------

function isMongoshStatementResult(
  value: unknown,
): value is MongoshStatementResult {
  if (typeof value !== "object" || value === null) return false;
  const kind = (value as { kind?: unknown }).kind;
  return (
    kind === "admin-command" ||
    kind === "collection-command" ||
    kind === "error"
  );
}

function parseMongoshCompletionVocabulary(
  value: unknown,
): MongoshCompletionVocabulary | null {
  if (typeof value !== "string") return null;
  const groups = value.split(MONGOSH_VOCABULARY_GROUP_SEPARATOR);
  if (groups.length !== 10) return null;
  const [
    queryGroup,
    projectionGroup,
    updateGroup,
    aggregateStageGroup,
    accumulatorGroup,
    expressionGroup,
    typeTagGroup,
    collectionMethodGroup,
    dbMethodGroup,
    adminCommandGroup,
  ] = groups as [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ];

  const queryOperators = splitVocabulary(queryGroup);
  const projectionOperators = splitVocabulary(projectionGroup);
  const updateOperators = splitVocabulary(updateGroup);
  const aggregateStages = splitVocabulary(aggregateStageGroup);
  const accumulators = splitVocabulary(accumulatorGroup);
  const expressionOperators = splitVocabulary(expressionGroup);
  const typeTags = splitVocabulary(typeTagGroup);

  return {
    queryOperators,
    projectionOperators,
    updateOperators,
    aggregateStages,
    accumulators,
    expressionOperators,
    typeTags,
    allOperators: [
      ...queryOperators,
      ...projectionOperators,
      ...updateOperators,
      ...aggregateStages,
      ...accumulators,
      ...expressionOperators,
      ...typeTags,
    ],
    mongoshCollectionMethods: splitVocabulary(collectionMethodGroup),
    mongoshDbMethods: splitVocabulary(dbMethodGroup),
    mongoAdminCommands: splitVocabulary(adminCommandGroup),
  };
}

function splitVocabulary(value: string): readonly string[] {
  return value.length === 0 ? [] : value.split("\n");
}

/**
 * Test-only escape hatch — `mongoshAst.test.ts` uses it to reset the
 * memoized module promise between test files. Not part of the public
 * surface.
 */
export function __resetMongoshWasmModuleForTests(): void {
  modulePromise = null;
  wasmModule = null;
}
