-- Canonical Oracle E2E seed.
--
-- Idempotency contract: re-running this file against an already-seeded
-- schema MUST exit 0. Execute with sqlplus/sqlcl against the target service.
--
-- Oracle keeps a real schema layer. The connected user owns these tables,
-- so object lookups should treat the current user as the schema.

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    total NUMBER(10, 2)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    price NUMBER(10, 2)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE VIEW active_oracle_users AS
  SELECT id, name, email
  FROM users
  WHERE email IS NOT NULL;
/

CREATE OR REPLACE FUNCTION oracle_catalog_ping RETURN NUMBER AS
BEGIN
  RETURN 1;
END;
/

MERGE INTO users u
USING (SELECT 'Alice' AS name, 'alice@example.com' AS email FROM dual) s
ON (u.email = s.email)
WHEN NOT MATCHED THEN INSERT (name, email) VALUES (s.name, s.email);

MERGE INTO users u
USING (SELECT 'Bob' AS name, 'bob@example.com' AS email FROM dual) s
ON (u.email = s.email)
WHEN NOT MATCHED THEN INSERT (name, email) VALUES (s.name, s.email);

INSERT INTO orders (user_id, total)
  SELECT 1, 99.99 FROM dual
  WHERE NOT EXISTS (
    SELECT 1 FROM orders WHERE user_id = 1 AND total = 99.99
  );

INSERT INTO products (name, price)
  SELECT 'Widget', 19.99 FROM dual
  WHERE NOT EXISTS (
    SELECT 1 FROM products WHERE name = 'Widget' AND price = 19.99
  );

COMMIT;
