export const MONGO_OPERATOR_META: Record<
  string,
  { detail: string; info: string }
> = {
  $eq: { detail: "value", info: "Matches values equal to the operand." },
  $ne: { detail: "value", info: "Matches values not equal to the operand." },
  $gt: { detail: "value", info: "Strictly greater than the operand." },
  $gte: { detail: "value", info: "Greater than or equal to the operand." },
  $lt: { detail: "value", info: "Strictly less than the operand." },
  $lte: { detail: "value", info: "Less than or equal to the operand." },
  $in: { detail: "[...]", info: "Matches any value in the given array." },
  $nin: { detail: "[...]", info: "Matches values not in the given array." },
  $and: { detail: "[expr,...]", info: "All sub-expressions must match." },
  $or: {
    detail: "[expr,...]",
    info: "At least one sub-expression must match.",
  },
  $nor: { detail: "[expr,...]", info: "None of the sub-expressions match." },
  $not: { detail: "expr", info: "Negates the inner expression." },
  $exists: { detail: "boolean", info: "Field exists or is absent." },
  $type: {
    detail: "bsonType",
    info: "Matches documents where the field has the given BSON type.",
  },
  $regex: {
    detail: "regex",
    info: "Matches strings against a regular expression.",
  },
  $elemMatch: {
    detail: "{...}",
    info: "At least one array element matches the inner expression.",
  },
  $size: {
    detail: "number",
    info: "Matches arrays of exactly the given length.",
  },
  $all: { detail: "[...]", info: "Array contains every listed value." },
  $match: { detail: "{filter}", info: "Filter matching documents." },
  $project: { detail: "{spec}", info: "Reshape output documents." },
  $group: {
    detail: "{_id, ...}",
    info: "Group documents and apply accumulators.",
  },
  $sort: {
    detail: "{field: 1|-1}",
    info: "Sort the pipeline or update array.",
  },
  $limit: { detail: "n", info: "Keep only the first n documents." },
  $skip: { detail: "n", info: "Skip the first n documents." },
  $unwind: { detail: "$path", info: "Emit one document per array element." },
  $lookup: { detail: "{from, localField, ...}", info: "Left-outer join." },
  $count: { detail: '"name"', info: "Count documents into a named field." },
  $addFields: { detail: "{spec}", info: "Append computed fields." },
  $replaceRoot: { detail: "{newRoot}", info: "Replace the document root." },
  $facet: {
    detail: "{name: [stages]}",
    info: "Run sub-pipelines in parallel.",
  },
  $out: { detail: '"coll"', info: "Write pipeline output to a collection." },
  $merge: {
    detail: "{into, ...}",
    info: "Merge pipeline output into a collection.",
  },
  $sum: { detail: "expr", info: "Sum numeric values." },
  $avg: { detail: "expr", info: "Average numeric values." },
  $min: { detail: "expr", info: "Minimum value." },
  $max: { detail: "expr", info: "Maximum value." },
  $push: { detail: "expr", info: "Append expression values to an array." },
  $addToSet: {
    detail: "expr",
    info: "Append deduplicated values to an array.",
  },
  $first: { detail: "expr", info: "First value encountered." },
  $last: { detail: "expr", info: "Last value encountered." },
  $oid: { detail: '"hex"', info: "ObjectId literal." },
  $date: { detail: "ISO|epoch", info: "Extended JSON date literal." },
  $numberLong: { detail: '"int64"', info: "64-bit signed integer literal." },
  $numberDouble: { detail: '"double"', info: "Double literal." },
  $numberInt: { detail: '"int32"', info: "32-bit integer literal." },
  $numberDecimal: { detail: '"decimal"', info: "Decimal128 literal." },
  $binary: { detail: "{base64, subType}", info: "Binary blob with subtype." },
  $regularExpression: {
    detail: "{pattern, options}",
    info: "BSON regex literal.",
  },
  $timestamp: { detail: "{t, i}", info: "Replication timestamp." },
  $minKey: { detail: "1", info: "Lower bound sentinel." },
  $maxKey: { detail: "1", info: "Upper bound sentinel." },
  $symbol: { detail: '"sym"', info: "Deprecated BSON symbol type." },
  $code: { detail: '"js"', info: "Server-side JavaScript code literal." },
};
