import {
  getMongoshCompletionVocabulary,
  type MongoshCompletionVocabulary,
} from "./mongoshAst";
import {
  MONGO_ADMIN_COMMANDS,
  MONGOSH_DB_LEVEL_METHODS,
  MONGOSH_DB_METHODS,
} from "./mongoShellCompletionVocabulary";

/**
 * MongoDB MQL completion vocabulary.
 *
 * Rust/WASM is the source of truth. The arrays in this module are a
 * compatibility mirror used before the eager-loaded WASM module is ready and
 * by tests/importers that need plain constants.
 */

export const MONGO_QUERY_OPERATORS = [
  "$all",
  "$and",
  "$bitsAllClear",
  "$bitsAllSet",
  "$bitsAnyClear",
  "$bitsAnySet",
  "$elemMatch",
  "$eq",
  "$exists",
  "$expr",
  "$geoIntersects",
  "$geoWithin",
  "$gt",
  "$gte",
  "$in",
  "$jsonSchema",
  "$lt",
  "$lte",
  "$mod",
  "$ne",
  "$near",
  "$nearSphere",
  "$nin",
  "$nor",
  "$not",
  "$or",
  "$regex",
  "$size",
  "$text",
  "$type",
  "$where",
] as const;

export const MONGO_PROJECTION_OPERATORS = [
  "$",
  "$elemMatch",
  "$meta",
  "$slice",
] as const;

export const MONGO_UPDATE_OPERATORS = [
  "$",
  "$[]",
  "$[<identifier>]",
  "$addToSet",
  "$bit",
  "$currentDate",
  "$each",
  "$inc",
  "$max",
  "$min",
  "$mul",
  "$pop",
  "$position",
  "$pull",
  "$pullAll",
  "$push",
  "$rename",
  "$set",
  "$setOnInsert",
  "$slice",
  "$sort",
  "$unset",
] as const;

export const MONGO_AGGREGATE_STAGES = [
  "$addFields",
  "$bucket",
  "$bucketAuto",
  "$changeStream",
  "$changeStreamSplitLargeEvent",
  "$collStats",
  "$count",
  "$currentOp",
  "$densify",
  "$documents",
  "$facet",
  "$fill",
  "$geoNear",
  "$graphLookup",
  "$group",
  "$indexStats",
  "$limit",
  "$listClusterCatalog",
  "$listLocalSessions",
  "$listSampledQueries",
  "$listSearchIndexes",
  "$listSessions",
  "$lookup",
  "$match",
  "$merge",
  "$out",
  "$planCacheStats",
  "$project",
  "$querySettings",
  "$queryStats",
  "$rankFusion",
  "$redact",
  "$replaceRoot",
  "$replaceWith",
  "$sample",
  "$score",
  "$scoreFusion",
  "$search",
  "$searchMeta",
  "$set",
  "$setWindowFields",
  "$shardedDataDistribution",
  "$skip",
  "$sort",
  "$sortByCount",
  "$unionWith",
  "$unset",
  "$unwind",
  "$vectorSearch",
] as const;

export const MONGO_ACCUMULATORS = [
  "$accumulator",
  "$addToSet",
  "$avg",
  "$bottom",
  "$bottomN",
  "$count",
  "$covariancePop",
  "$covarianceSamp",
  "$derivative",
  "$expMovingAvg",
  "$first",
  "$firstN",
  "$integral",
  "$last",
  "$lastN",
  "$max",
  "$maxN",
  "$median",
  "$mergeObjects",
  "$min",
  "$minN",
  "$percentile",
  "$push",
  "$stdDevPop",
  "$stdDevSamp",
  "$sum",
  "$top",
  "$topN",
] as const;

export const MONGO_EXPRESSION_OPERATORS = [
  "$abs",
  "$acos",
  "$acosh",
  "$add",
  "$allElementsTrue",
  "$and",
  "$anyElementTrue",
  "$arrayElemAt",
  "$arrayToObject",
  "$asin",
  "$asinh",
  "$atan",
  "$atan2",
  "$atanh",
  "$avg",
  "$binarySize",
  "$bitAnd",
  "$bitNot",
  "$bitOr",
  "$bitXor",
  "$bottom",
  "$bottomN",
  "$bsonSize",
  "$ceil",
  "$cmp",
  "$concat",
  "$concatArrays",
  "$cond",
  "$const",
  "$convert",
  "$cos",
  "$cosh",
  "$dateAdd",
  "$dateDiff",
  "$dateFromParts",
  "$dateFromString",
  "$dateSubtract",
  "$dateToParts",
  "$dateToString",
  "$dateTrunc",
  "$dayOfMonth",
  "$dayOfWeek",
  "$dayOfYear",
  "$degreesToRadians",
  "$denseRank",
  "$derivative",
  "$divide",
  "$documentNumber",
  "$eq",
  "$exp",
  "$expMovingAvg",
  "$filter",
  "$first",
  "$firstN",
  "$floor",
  "$function",
  "$getField",
  "$gt",
  "$gte",
  "$hour",
  "$ifNull",
  "$in",
  "$indexOfArray",
  "$indexOfBytes",
  "$indexOfCP",
  "$integral",
  "$isArray",
  "$isoDayOfWeek",
  "$isoWeek",
  "$isoWeekYear",
  "$last",
  "$lastN",
  "$let",
  "$literal",
  "$ln",
  "$log",
  "$log10",
  "$lt",
  "$lte",
  "$ltrim",
  "$map",
  "$max",
  "$maxN",
  "$median",
  "$mergeObjects",
  "$meta",
  "$min",
  "$minN",
  "$millisecond",
  "$minute",
  "$mod",
  "$month",
  "$multiply",
  "$ne",
  "$not",
  "$objectToArray",
  "$or",
  "$percentile",
  "$pow",
  "$push",
  "$radiansToDegrees",
  "$rand",
  "$range",
  "$rank",
  "$reduce",
  "$regexFind",
  "$regexFindAll",
  "$regexMatch",
  "$replaceAll",
  "$replaceOne",
  "$reverseArray",
  "$round",
  "$rtrim",
  "$sampleRate",
  "$second",
  "$setDifference",
  "$setEquals",
  "$setField",
  "$setIntersection",
  "$setIsSubset",
  "$setUnion",
  "$shift",
  "$sin",
  "$sinh",
  "$size",
  "$slice",
  "$sortArray",
  "$split",
  "$sqrt",
  "$stdDevPop",
  "$stdDevSamp",
  "$strcasecmp",
  "$strLenBytes",
  "$strLenCP",
  "$substr",
  "$substrBytes",
  "$substrCP",
  "$subtract",
  "$sum",
  "$switch",
  "$tan",
  "$tanh",
  "$toBool",
  "$toDate",
  "$toDecimal",
  "$toDouble",
  "$toHashedIndexKey",
  "$toInt",
  "$toLong",
  "$toLower",
  "$toObjectId",
  "$toString",
  "$toUUID",
  "$toUpper",
  "$trim",
  "$trunc",
  "$tsIncrement",
  "$tsSecond",
  "$type",
  "$unsetField",
  "$week",
  "$year",
  "$zip",
] as const;

export const MONGO_TYPE_TAGS = [
  "$oid",
  "$date",
  "$numberLong",
  "$numberDouble",
  "$numberInt",
  "$numberDecimal",
  "$binary",
  "$regularExpression",
  "$timestamp",
  "$minKey",
  "$maxKey",
  "$symbol",
  "$code",
  "$uuid",
] as const;

export const MONGO_ALL_OPERATORS: readonly string[] = [
  ...MONGO_QUERY_OPERATORS,
  ...MONGO_PROJECTION_OPERATORS,
  ...MONGO_UPDATE_OPERATORS,
  ...MONGO_AGGREGATE_STAGES,
  ...MONGO_ACCUMULATORS,
  ...MONGO_EXPRESSION_OPERATORS,
  ...MONGO_TYPE_TAGS,
];

const FALLBACK_VOCABULARY: MongoshCompletionVocabulary = {
  queryOperators: MONGO_QUERY_OPERATORS,
  projectionOperators: MONGO_PROJECTION_OPERATORS,
  updateOperators: MONGO_UPDATE_OPERATORS,
  aggregateStages: MONGO_AGGREGATE_STAGES,
  accumulators: MONGO_ACCUMULATORS,
  expressionOperators: MONGO_EXPRESSION_OPERATORS,
  typeTags: MONGO_TYPE_TAGS,
  allOperators: MONGO_ALL_OPERATORS,
  mongoshCollectionMethods: MONGOSH_DB_METHODS.map((method) => method.label),
  mongoshDbMethods: MONGOSH_DB_LEVEL_METHODS.map((method) => method.label),
  mongoAdminCommands: MONGO_ADMIN_COMMANDS.map((command) => command.label),
};

export function getMongoCompletionVocabulary(): MongoshCompletionVocabulary {
  return getMongoshCompletionVocabulary() ?? FALLBACK_VOCABULARY;
}
