/**
 * `schemaDialogs` 네임스페이스 — schema 관련 DDL dialog 문자열.
 *
 * en 값은 마이그레이션 이전 하드코딩 영어 리터럴을 바이트 그대로 미러한다 —
 * 기본 locale 이 en 이므로 렌더/테스트/E2E 선택자가 불변이다.
 */

export const en = {
  // ── 공통 버튼 / 액션 ─────────────────────────────────────────
  cancel: "Cancel",
  apply: "Apply",
  execute: "Execute",
  hideDdl: "Hide DDL",
  showDdl: "Show DDL",
  generatingPreview: "Generating preview…",
  closeDialog: "Close dialog",

  // ── DDL preview 빈 상태 힌트 ──────────────────────────────────
  ddlHintFillForm: "-- Fill in the form to see the generated SQL",
  ddlHintFillNameType: "-- Fill in name + type to see the generated SQL",
  ddlHintFillTrigger:
    "-- Fill in trigger name + function to see the generated SQL",
  ddlHintTypeTableName: "-- Type the table name to see the generated SQL",
  ddlHintTypeColumnName: "-- Type the column name to see the generated SQL",
  ddlHintTypeTriggerName: "-- Type the trigger name to see the generated SQL",
  ddlHintTypeNewName: "-- Type a new name to see the generated SQL",

  // ── CreateTableDialog ─────────────────────────────────────────
  createTable: {
    title: "Create Table",
    descriptionAria: "Create a new table in {{schema}}",
    targetSchemaLabel: "Target schema",
    targetSchemaAria: "Target schema",
    tableNameLabel: "Table name",
    tableNameAria: "Table name",
    tableCommentLabel: "Table comment",
    tableCommentPlaceholder: "comment (optional)",
    tableCommentAria: "Table comment",
    tabColumns: "Columns",
    tabKeys: "Keys",
    tabIndexes: "Indexes",
    tabConstraints: "Constraints",
    columnsLabel: "Columns",
    addColumnAria: "Add column",
    addColumnBtn: "Column",
    columnNamePlaceholder: "column_name",
    columnNameAria: "Column name",
    columnNullableAria: "Column nullable",
    columnNullableLabel: "Nullable",
    columnIdentityAria: "Column identity",
    columnIdentityLabel: "Identity",
    columnIdentityTitle:
      "Auto-incrementing identity column (PG: GENERATED BY DEFAULT AS IDENTITY)",
    columnDefaultPlaceholder: "default value (optional)",
    columnDefaultIdentityPlaceholder: "(IDENTITY sequence)",
    columnDefaultAria: "Column default value",
    columnCommentPlaceholder: "comment (optional)",
    columnCommentAria: "Column comment",
    columnCheckPlaceholder: "check expression (optional, e.g. age >= 0)",
    columnCheckAria: "Column check expression",
    moveColumnUpAria: "Move column up",
    moveColumnUpTitle: "Move column up",
    moveColumnDownAria: "Move column down",
    moveColumnDownTitle: "Move column down",
    removeColumnAria: "Remove column",
    removeColumnTitle: "Remove column",
    removeColumnDisabledTitle: "At least one column required",
    primaryKeyLabel: "Primary key",
    primaryKeyColumnsAria: "Primary key columns",
    primaryKeyEmptyHint:
      "Add named columns in the Columns tab to use this picker.",
    primaryKeyColAria: "Primary key: {{colName}}",
  },

  // ── CreateTriggerDialog ───────────────────────────────────────
  createTrigger: {
    title: "Create Trigger",
    triggerNameLabel: "Trigger name",
    triggerNamePlaceholder: "trigger_name",
    triggerNameAria: "Trigger name",
    triggerNameErrorAria: "Trigger name validation error",
    timingLabel: "Timing",
    timingGroupAria: "Timing",
    timingOptionAria: "Timing {{option}}",
    eventsLabel: "Events",
    eventsGroupAria: "Events",
    eventOptionAria: "Event {{event}}",
    eventsErrorAria: "Events validation error",
    selectAtLeastOneEvent: "Select at least one event",
    insteadOfMultiEvent: "INSTEAD OF triggers must declare exactly one event",
    insteadOfMultiEventAria: "INSTEAD OF multi-event error",
    insteadOfStatement: "INSTEAD OF triggers must use FOR EACH ROW",
    insteadOfStatementAria: "INSTEAD OF statement error",
    orientationLabel: "For each",
    orientationGroupAria: "Orientation",
    orientationOptionAria: "Orientation {{option}}",
    whenLabel: "WHEN (optional)",
    whenAria: "WHEN expression",
    whenPlaceholder: "e.g. NEW.email IS DISTINCT FROM OLD.email",
    executeFunctionLabel: "Execute function",
    functionSchemaPlaceholder: "schema",
    functionSchemaAria: "Function schema",
    functionSchemaErrorAria: "Function schema validation error",
    functionNamePlaceholder: "function_name",
    functionNameAria: "Function name",
    functionNameErrorAria: "Function name validation error",
    argumentsLabel: "Arguments (optional)",
    argumentsPlaceholder: "e.g. 'arg1', 'arg2'",
    argumentsAria: "Function arguments",
    applyAria: "Apply",
  },

  // ── AddColumnDialog ───────────────────────────────────────────
  addColumn: {
    title: "Add Column",
    columnNameLabel: "Column name",
    columnNamePlaceholder: "column_name",
    columnNameAria: "Column name",
    identifierErrorAria: "Identifier validation error",
    columnCollisionAria: "Column name collision",
    columnAlreadyExists: 'Column "{{name}}" already exists',
    typeLabel: "Type",
    typeAria: "Column data type",
    notNullAria: "NOT NULL",
    notNullLabel: "NOT NULL",
    identityAria: "Identity",
    identityLabel: "Identity",
    identityTitle:
      "Auto-incrementing identity column (PG: GENERATED BY DEFAULT AS IDENTITY)",
    defaultLabel: "DEFAULT (optional)",
    defaultPlaceholder: "e.g. 0, now(), 'pending'",
    defaultIdentityPlaceholder: "(IDENTITY sequence)",
    defaultAria: "DEFAULT expression",
    checkLabel: "CHECK (optional)",
    checkPlaceholder: "e.g. age >= 0",
    checkAria: "CHECK expression",
    applyAria: "Apply",
  },

  // ── DropTableDialog ───────────────────────────────────────────
  dropTable: {
    title: "Drop Table",
    warningText:
      "This action cannot be undone. Type the table name to confirm.",
    typingConfirmLabel: "Type the table name to confirm",
    typingConfirmAria: "Type the table name to confirm",
    cascadeAria: "CASCADE",
    cascadeLabel: "CASCADE — drop dependent objects (default: off)",
    applyAria: "Apply",
  },

  // ── DropColumnDialog ──────────────────────────────────────────
  dropColumn: {
    title: "Drop Column",
    warningText:
      "This action cannot be undone. Type the column name to confirm.",
    typingConfirmLabel: "Type the column name to confirm",
    typingConfirmAria: "Type the column name to confirm",
    cascadeAria: "CASCADE",
    cascadeLabel: "Drop dependent objects (CASCADE)",
    applyAria: "Apply",
  },

  // ── DropTriggerDialog ─────────────────────────────────────────
  dropTrigger: {
    title: "Drop Trigger",
    warningText:
      "This action cannot be undone. Type the trigger name to confirm.",
    typingConfirmLabel: "Type the trigger name to confirm",
    typingConfirmAria: "Type the trigger name to confirm",
    cascadeAria: "CASCADE",
    cascadeLabel: "CASCADE — drop dependent objects (default: off)",
    applyAria: "Apply",
  },

  // ── RenameTableDialog ─────────────────────────────────────────
  renameTable: {
    title: "Rename Table",
    newNameLabel: "New table name",
    newNamePlaceholder: "new_table_name",
    newNameAria: "New table name",
    identifierErrorAria: "Identifier validation error",
    applyAria: "Apply",
  },

  // ── IndexesTabBody ────────────────────────────────────────────
  indexesTab: {
    label: "Indexes",
    addAria: "Add index",
    addBtn: "Index",
    emptyHint:
      'No indexes declared. PostgreSQL implicitly indexes primary-key columns; click "+ Index" to declare additional indexes.',
    indexNamePlaceholder: "index_name",
    indexNameAria: "Index name",
    indexTypeAria: "Index type",
    indexUniqueAria: "Index unique",
    indexUniqueLabel: "Unique",
    pkSkippedHint: "Skipped — primary key is already indexed",
    moveUpAria: "Move index up",
    moveUpTitle: "Move index up",
    moveDownAria: "Move index down",
    moveDownTitle: "Move index down",
    removeAria: "Remove index",
    removeTitle: "Remove index",
  },

  // ── ForeignKeysTabBody ────────────────────────────────────────
  constraintsTab: {
    // sub-tab labels
    foreignKeysTab: "Foreign Keys",
    checkTab: "CHECK",
    uniqueTab: "UNIQUE",

    // FK section
    fkScopeNote:
      "Single-column foreign keys are edited inline on the column row (Columns tab). Use this tab when the FK spans multiple local columns (e.g. composite FK).",
    fkSectionLabel: "Foreign Keys",
    addFkAria: "Add foreign key",
    addFkBtn: "Foreign Key",
    fkEmptyHint: 'No foreign keys declared. Click "+ Foreign Key" to add one.',
    fkNamePlaceholder: "fk_table_column",
    fkNameAria: "Foreign key name",
    fkRefSchemaAria: "Foreign key reference schema",
    fkRefTableAria: "Foreign key reference table",
    fkRefTablePlaceholder: "reference_table_name",
    fkRefColumnsAria: "Foreign key reference columns",
    fkRefColumnsPickTableHint:
      "Pick a reference table to choose reference columns",
    fkRefColumnsLoadingHint: "Loading reference columns…",
    fkRefColumnsTextAria: "Foreign key reference columns text",
    fkRefColumnsNoAvailable: "No reference columns available",
    fkOnDeleteLabel: "ON DELETE",
    fkOnDeleteAria: "Foreign key on delete",
    fkOnUpdateLabel: "ON UPDATE",
    fkOnUpdateAria: "Foreign key on update",
    moveFkUpAria: "Move foreign key up",
    moveFkUpTitle: "Move foreign key up",
    moveFkDownAria: "Move foreign key down",
    moveFkDownTitle: "Move foreign key down",
    removeFkAria: "Remove foreign key",
    removeFkTitle: "Remove foreign key",

    // CHECK section
    checkScopeNote:
      "Single-column CHECK expressions live inline on the column row (Columns tab). Use this tab for CHECK expressions that reference multiple columns (e.g. start_at < end_at).",
    checkSectionLabel: "CHECK constraints",
    addCheckAria: "Add check",
    addCheckBtn: "CHECK",
    checkEmptyHint:
      'No CHECK constraints declared. Click "+ CHECK" to add one.',
    checkNamePlaceholder: "chk_table_n",
    checkNameAria: "Check name",
    checkExprPlaceholder: "age >= 0",
    checkExprAria: "Check expression",
    moveCheckUpAria: "Move check up",
    moveCheckUpTitle: "Move check up",
    moveCheckDownAria: "Move check down",
    moveCheckDownTitle: "Move check down",
    removeCheckAria: "Remove check",
    removeCheckTitle: "Remove check",

    // UNIQUE section
    uniqueScopeNote:
      "Per-column uniqueness is set in the Keys tab (mark the column as PK) or via a single-column UNIQUE row here. Use this tab when uniqueness must hold across multiple columns together (e.g. (tenant_id, email)).",
    uniqueSectionLabel: "Unique constraints",
    addUniqueAria: "Add unique",
    addUniqueBtn: "Unique",
    uniqueEmptyHint:
      'No table-level UNIQUE constraints declared. Click "+ Unique" to add one.',
    uniqueNamePlaceholder: "uq_table_columns",
    uniqueNameAria: "Unique name",
    moveUniqueUpAria: "Move unique up",
    moveUniqueUpTitle: "Move unique up",
    moveUniqueDownAria: "Move unique down",
    moveUniqueDownTitle: "Move unique down",
    removeUniqueAria: "Remove unique",
    removeUniqueTitle: "Remove unique",
  },

  // ── InlineFkPopover ───────────────────────────────────────────
  inlineFk: {
    triggerNoFkTitle: "Add inline foreign key",
    columnFkAria: "Foreign key for column {{trackingId}}",
    popoverTitle: "Foreign key",
    clearAria: "Clear inline foreign key",
    clearTitle: "Clear FK",
    refSchemaLabel: "Reference schema",
    refSchemaAria: "Inline FK reference schema",
    refTableLabel: "Reference table",
    refTablePickAria: "Inline FK reference table",
    refTableInputAria: "Inline FK reference table",
    refTableInputPlaceholder: "reference_table",
    refColumnLabel: "Reference column",
    refColumnPickAria: "Inline FK reference column",
    refColumnInputAria: "Inline FK reference column",
    refColumnInputPlaceholder: "reference_column",
    onDeleteLabel: "ON DELETE",
    onDeleteAria: "Inline FK on delete",
    onUpdateLabel: "ON UPDATE",
    onUpdateAria: "Inline FK on update",
  },

  // ── CreateTableTypeCombobox ───────────────────────────────────
  typeCombobox: {
    defaultAriaLabel: "Column data type",
    defaultPlaceholder: "varchar(255)",
    showTypesAria: "Show types",
    listboxAria: "PostgreSQL types",
  },
} as const;

export const ko = {
  // ── 공통 버튼 / 액션 ─────────────────────────────────────────
  cancel: "취소",
  apply: "적용",
  execute: "실행",
  hideDdl: "DDL 숨기기",
  showDdl: "DDL 보기",
  generatingPreview: "미리보기 생성 중…",
  closeDialog: "다이얼로그 닫기",

  // ── DDL preview 빈 상태 힌트 ──────────────────────────────────
  ddlHintFillForm: "-- 양식을 채우면 생성된 SQL을 볼 수 있습니다",
  ddlHintFillNameType: "-- 이름과 타입을 입력하면 생성된 SQL을 볼 수 있습니다",
  ddlHintFillTrigger:
    "-- 트리거 이름과 함수를 입력하면 생성된 SQL을 볼 수 있습니다",
  ddlHintTypeTableName: "-- 테이블 이름을 입력하면 생성된 SQL을 볼 수 있습니다",
  ddlHintTypeColumnName: "-- 컬럼 이름을 입력하면 생성된 SQL을 볼 수 있습니다",
  ddlHintTypeTriggerName:
    "-- 트리거 이름을 입력하면 생성된 SQL을 볼 수 있습니다",
  ddlHintTypeNewName: "-- 새 이름을 입력하면 생성된 SQL을 볼 수 있습니다",

  // ── CreateTableDialog ─────────────────────────────────────────
  createTable: {
    title: "테이블 생성",
    descriptionAria: "{{schema}}에 새 테이블을 생성합니다",
    targetSchemaLabel: "대상 스키마",
    targetSchemaAria: "대상 스키마",
    tableNameLabel: "테이블 이름",
    tableNameAria: "테이블 이름",
    tableCommentLabel: "테이블 주석",
    tableCommentPlaceholder: "주석 (선택사항)",
    tableCommentAria: "테이블 주석",
    tabColumns: "컬럼",
    tabKeys: "키",
    tabIndexes: "인덱스",
    tabConstraints: "제약조건",
    columnsLabel: "컬럼",
    addColumnAria: "컬럼 추가",
    addColumnBtn: "컬럼",
    columnNamePlaceholder: "column_name",
    columnNameAria: "컬럼 이름",
    columnNullableAria: "컬럼 널 허용",
    columnNullableLabel: "Nullable",
    columnIdentityAria: "컬럼 Identity",
    columnIdentityLabel: "Identity",
    columnIdentityTitle:
      "자동 증가 Identity 컬럼 (PG: GENERATED BY DEFAULT AS IDENTITY)",
    columnDefaultPlaceholder: "기본값 (선택사항)",
    columnDefaultIdentityPlaceholder: "(IDENTITY 시퀀스)",
    columnDefaultAria: "컬럼 기본값",
    columnCommentPlaceholder: "주석 (선택사항)",
    columnCommentAria: "컬럼 주석",
    columnCheckPlaceholder: "CHECK 표현식 (선택사항, 예: age >= 0)",
    columnCheckAria: "컬럼 CHECK 표현식",
    moveColumnUpAria: "컬럼 위로 이동",
    moveColumnUpTitle: "컬럼 위로 이동",
    moveColumnDownAria: "컬럼 아래로 이동",
    moveColumnDownTitle: "컬럼 아래로 이동",
    removeColumnAria: "컬럼 제거",
    removeColumnTitle: "컬럼 제거",
    removeColumnDisabledTitle: "최소 하나의 컬럼이 필요합니다",
    primaryKeyLabel: "기본 키",
    primaryKeyColumnsAria: "기본 키 컬럼",
    primaryKeyEmptyHint: "컬럼 탭에서 이름이 있는 컬럼을 추가하여 사용하세요.",
    primaryKeyColAria: "기본 키: {{colName}}",
  },

  // ── CreateTriggerDialog ───────────────────────────────────────
  createTrigger: {
    title: "트리거 생성",
    triggerNameLabel: "트리거 이름",
    triggerNamePlaceholder: "trigger_name",
    triggerNameAria: "트리거 이름",
    triggerNameErrorAria: "트리거 이름 유효성 오류",
    timingLabel: "타이밍",
    timingGroupAria: "타이밍",
    timingOptionAria: "타이밍 {{option}}",
    eventsLabel: "이벤트",
    eventsGroupAria: "이벤트",
    eventOptionAria: "이벤트 {{event}}",
    eventsErrorAria: "이벤트 유효성 오류",
    selectAtLeastOneEvent: "최소 하나의 이벤트를 선택하세요",
    insteadOfMultiEvent:
      "INSTEAD OF 트리거는 정확히 하나의 이벤트만 선언해야 합니다",
    insteadOfMultiEventAria: "INSTEAD OF 다중 이벤트 오류",
    insteadOfStatement: "INSTEAD OF 트리거는 FOR EACH ROW를 사용해야 합니다",
    insteadOfStatementAria: "INSTEAD OF STATEMENT 오류",
    orientationLabel: "각각에 대해",
    orientationGroupAria: "지향성",
    orientationOptionAria: "지향성 {{option}}",
    whenLabel: "WHEN (선택사항)",
    whenAria: "WHEN 표현식",
    whenPlaceholder: "예: NEW.email IS DISTINCT FROM OLD.email",
    executeFunctionLabel: "실행 함수",
    functionSchemaPlaceholder: "schema",
    functionSchemaAria: "함수 스키마",
    functionSchemaErrorAria: "함수 스키마 유효성 오류",
    functionNamePlaceholder: "function_name",
    functionNameAria: "함수 이름",
    functionNameErrorAria: "함수 이름 유효성 오류",
    argumentsLabel: "인수 (선택사항)",
    argumentsPlaceholder: "예: 'arg1', 'arg2'",
    argumentsAria: "함수 인수",
    applyAria: "적용",
  },

  // ── AddColumnDialog ───────────────────────────────────────────
  addColumn: {
    title: "컬럼 추가",
    columnNameLabel: "컬럼 이름",
    columnNamePlaceholder: "column_name",
    columnNameAria: "컬럼 이름",
    identifierErrorAria: "식별자 유효성 오류",
    columnCollisionAria: "컬럼 이름 충돌",
    columnAlreadyExists: '"{{name}}" 컬럼이 이미 존재합니다',
    typeLabel: "타입",
    typeAria: "컬럼 데이터 타입",
    notNullAria: "NOT NULL",
    notNullLabel: "NOT NULL",
    identityAria: "Identity",
    identityLabel: "Identity",
    identityTitle:
      "자동 증가 Identity 컬럼 (PG: GENERATED BY DEFAULT AS IDENTITY)",
    defaultLabel: "DEFAULT (선택사항)",
    defaultPlaceholder: "예: 0, now(), 'pending'",
    defaultIdentityPlaceholder: "(IDENTITY 시퀀스)",
    defaultAria: "DEFAULT 표현식",
    checkLabel: "CHECK (선택사항)",
    checkPlaceholder: "예: age >= 0",
    checkAria: "CHECK 표현식",
    applyAria: "적용",
  },

  // ── DropTableDialog ───────────────────────────────────────────
  dropTable: {
    title: "테이블 삭제",
    warningText:
      "이 작업은 되돌릴 수 없습니다. 확인을 위해 테이블 이름을 입력하세요.",
    typingConfirmLabel: "확인을 위해 테이블 이름을 입력하세요",
    typingConfirmAria: "확인을 위해 테이블 이름을 입력하세요",
    cascadeAria: "CASCADE",
    cascadeLabel: "CASCADE — 종속 객체 삭제 (기본값: 끄기)",
    applyAria: "적용",
  },

  // ── DropColumnDialog ──────────────────────────────────────────
  dropColumn: {
    title: "컬럼 삭제",
    warningText:
      "이 작업은 되돌릴 수 없습니다. 확인을 위해 컬럼 이름을 입력하세요.",
    typingConfirmLabel: "확인을 위해 컬럼 이름을 입력하세요",
    typingConfirmAria: "확인을 위해 컬럼 이름을 입력하세요",
    cascadeAria: "CASCADE",
    cascadeLabel: "종속 객체 삭제 (CASCADE)",
    applyAria: "적용",
  },

  // ── DropTriggerDialog ─────────────────────────────────────────
  dropTrigger: {
    title: "트리거 삭제",
    warningText:
      "이 작업은 되돌릴 수 없습니다. 확인을 위해 트리거 이름을 입력하세요.",
    typingConfirmLabel: "확인을 위해 트리거 이름을 입력하세요",
    typingConfirmAria: "확인을 위해 트리거 이름을 입력하세요",
    cascadeAria: "CASCADE",
    cascadeLabel: "CASCADE — 종속 객체 삭제 (기본값: 끄기)",
    applyAria: "적용",
  },

  // ── RenameTableDialog ─────────────────────────────────────────
  renameTable: {
    title: "테이블 이름 변경",
    newNameLabel: "새 테이블 이름",
    newNamePlaceholder: "new_table_name",
    newNameAria: "새 테이블 이름",
    identifierErrorAria: "식별자 유효성 오류",
    applyAria: "적용",
  },

  // ── IndexesTabBody ────────────────────────────────────────────
  indexesTab: {
    label: "인덱스",
    addAria: "인덱스 추가",
    addBtn: "인덱스",
    emptyHint:
      '선언된 인덱스가 없습니다. PostgreSQL은 기본 키 컬럼을 암묵적으로 인덱싱합니다. "+ Index"를 클릭하여 추가 인덱스를 선언하세요.',
    indexNamePlaceholder: "index_name",
    indexNameAria: "인덱스 이름",
    indexTypeAria: "인덱스 타입",
    indexUniqueAria: "인덱스 고유",
    indexUniqueLabel: "고유",
    pkSkippedHint: "건너뜀 — 기본 키는 이미 인덱싱되어 있습니다",
    moveUpAria: "인덱스 위로 이동",
    moveUpTitle: "인덱스 위로 이동",
    moveDownAria: "인덱스 아래로 이동",
    moveDownTitle: "인덱스 아래로 이동",
    removeAria: "인덱스 제거",
    removeTitle: "인덱스 제거",
  },

  // ── ForeignKeysTabBody ────────────────────────────────────────
  constraintsTab: {
    // sub-tab labels
    foreignKeysTab: "외래 키",
    checkTab: "CHECK",
    uniqueTab: "UNIQUE",

    // FK section
    fkScopeNote:
      "단일 컬럼 외래 키는 컬럼 행 인라인에서 편집합니다 (컬럼 탭). 여러 로컬 컬럼에 걸친 FK(예: 복합 FK)에는 이 탭을 사용하세요.",
    fkSectionLabel: "외래 키",
    addFkAria: "외래 키 추가",
    addFkBtn: "외래 키",
    fkEmptyHint:
      '선언된 외래 키가 없습니다. "+ Foreign Key"를 클릭하여 추가하세요.',
    fkNamePlaceholder: "fk_table_column",
    fkNameAria: "외래 키 이름",
    fkRefSchemaAria: "외래 키 참조 스키마",
    fkRefTableAria: "외래 키 참조 테이블",
    fkRefTablePlaceholder: "reference_table_name",
    fkRefColumnsAria: "외래 키 참조 컬럼",
    fkRefColumnsPickTableHint:
      "참조 컬럼을 선택하려면 참조 테이블을 먼저 선택하세요",
    fkRefColumnsLoadingHint: "참조 컬럼 로드 중…",
    fkRefColumnsTextAria: "외래 키 참조 컬럼 텍스트",
    fkRefColumnsNoAvailable: "사용 가능한 참조 컬럼이 없습니다",
    fkOnDeleteLabel: "ON DELETE",
    fkOnDeleteAria: "외래 키 ON DELETE",
    fkOnUpdateLabel: "ON UPDATE",
    fkOnUpdateAria: "외래 키 ON UPDATE",
    moveFkUpAria: "외래 키 위로 이동",
    moveFkUpTitle: "외래 키 위로 이동",
    moveFkDownAria: "외래 키 아래로 이동",
    moveFkDownTitle: "외래 키 아래로 이동",
    removeFkAria: "외래 키 제거",
    removeFkTitle: "외래 키 제거",

    // CHECK section
    checkScopeNote:
      "단일 컬럼 CHECK 표현식은 컬럼 행 인라인에 있습니다 (컬럼 탭). 여러 컬럼을 참조하는 CHECK 표현식에는 이 탭을 사용하세요 (예: start_at < end_at).",
    checkSectionLabel: "CHECK 제약조건",
    addCheckAria: "CHECK 추가",
    addCheckBtn: "CHECK",
    checkEmptyHint:
      '선언된 CHECK 제약조건이 없습니다. "+ CHECK"를 클릭하여 추가하세요.',
    checkNamePlaceholder: "chk_table_n",
    checkNameAria: "CHECK 이름",
    checkExprPlaceholder: "age >= 0",
    checkExprAria: "CHECK 표현식",
    moveCheckUpAria: "CHECK 위로 이동",
    moveCheckUpTitle: "CHECK 위로 이동",
    moveCheckDownAria: "CHECK 아래로 이동",
    moveCheckDownTitle: "CHECK 아래로 이동",
    removeCheckAria: "CHECK 제거",
    removeCheckTitle: "CHECK 제거",

    // UNIQUE section
    uniqueScopeNote:
      "컬럼별 고유성은 키 탭에서 설정합니다 (PK로 표시). 여러 컬럼에 걸쳐 고유성이 유지되어야 할 때 이 탭을 사용하세요 (예: (tenant_id, email)).",
    uniqueSectionLabel: "고유 제약조건",
    addUniqueAria: "고유 제약조건 추가",
    addUniqueBtn: "고유",
    uniqueEmptyHint:
      '선언된 테이블 수준 UNIQUE 제약조건이 없습니다. "+ Unique"를 클릭하여 추가하세요.',
    uniqueNamePlaceholder: "uq_table_columns",
    uniqueNameAria: "고유 이름",
    moveUniqueUpAria: "고유 제약조건 위로 이동",
    moveUniqueUpTitle: "고유 제약조건 위로 이동",
    moveUniqueDownAria: "고유 제약조건 아래로 이동",
    moveUniqueDownTitle: "고유 제약조건 아래로 이동",
    removeUniqueAria: "고유 제약조건 제거",
    removeUniqueTitle: "고유 제약조건 제거",
  },

  // ── InlineFkPopover ───────────────────────────────────────────
  inlineFk: {
    triggerNoFkTitle: "인라인 외래 키 추가",
    columnFkAria: "컬럼 {{trackingId}}의 외래 키",
    popoverTitle: "외래 키",
    clearAria: "인라인 외래 키 지우기",
    clearTitle: "FK 지우기",
    refSchemaLabel: "참조 스키마",
    refSchemaAria: "인라인 FK 참조 스키마",
    refTableLabel: "참조 테이블",
    refTablePickAria: "인라인 FK 참조 테이블",
    refTableInputAria: "인라인 FK 참조 테이블",
    refTableInputPlaceholder: "reference_table",
    refColumnLabel: "참조 컬럼",
    refColumnPickAria: "인라인 FK 참조 컬럼",
    refColumnInputAria: "인라인 FK 참조 컬럼",
    refColumnInputPlaceholder: "reference_column",
    onDeleteLabel: "ON DELETE",
    onDeleteAria: "인라인 FK ON DELETE",
    onUpdateLabel: "ON UPDATE",
    onUpdateAria: "인라인 FK ON UPDATE",
  },

  // ── CreateTableTypeCombobox ───────────────────────────────────
  typeCombobox: {
    defaultAriaLabel: "컬럼 데이터 타입",
    defaultPlaceholder: "varchar(255)",
    showTypesAria: "타입 보기",
    listboxAria: "PostgreSQL 타입",
  },
} as const;
