import { describe, it, expect, vi, beforeEach } from "vitest";
import { fireEvent, screen, waitFor, within } from "@testing-library/react";
import { useConnectionStore } from "@stores/connectionStore";
import { useSafeModeStore } from "@stores/safeModeStore";
import { useQueryHistoryStore } from "@stores/queryHistoryStore";
import {
  getColumnsPanel,
  mockCreateTable,
  renderDialog,
  setDevConnection,
} from "./__tests__/createTableDialogTestHelpers";

// ── Sprint 242 — IDENTITY (auto-increment) toggle ─────────────────────
//
// Date: 2026-05-08.
//
// Why these tests exist:
//
// Sprint 242 adds an `is_identity` flag to `ColumnDraft` + a per-row
// "Identity" checkbox. When checked, the dialog disables the row's
// `Nullable` + `default value` inputs (the IDENTITY sequence is the
// default; PG forces NOT NULL) and the `buildRequest` payload sets
// `is_identity: true` on the column's wire shape so the backend's PG
// emitter writes `GENERATED BY DEFAULT AS IDENTITY`.
describe("Sprint 242 — IDENTITY toggle on column row", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    useConnectionStore.setState({ connections: [] });
    useSafeModeStore.setState({ mode: "off" });
    useQueryHistoryStore.setState({ recentVisible: [] });
    mockCreateTable.mockResolvedValue({
      sql: 'CREATE TABLE "public"."t" ()',
    });
    setDevConnection();
  });

  it("renders the per-row Identity toggle next to Nullable", () => {
    renderDialog();
    const columnsPanel = getColumnsPanel();
    const identity = within(columnsPanel).getByLabelText("Column identity");
    expect(identity).toBeInTheDocument();
    expect((identity as HTMLInputElement).checked).toBe(false);
  });

  it("checking Identity disables Nullable + default-value inputs", () => {
    renderDialog();
    const columnsPanel = getColumnsPanel();
    fireEvent.click(within(columnsPanel).getByLabelText("Column identity"));
    expect(
      (
        within(columnsPanel).getByLabelText(
          "Column nullable",
        ) as HTMLInputElement
      ).disabled,
    ).toBe(true);
    expect(
      (
        within(columnsPanel).getByLabelText(
          "Column default value",
        ) as HTMLInputElement
      ).disabled,
    ).toBe(true);
  });

  it("identity column flows into createTable wire payload as is_identity: true", async () => {
    renderDialog();
    fireEvent.change(screen.getByLabelText("Table name"), {
      target: { value: "events" },
    });
    const columnsPanel = getColumnsPanel();
    fireEvent.change(within(columnsPanel).getByLabelText("Column name"), {
      target: { value: "id" },
    });
    fireEvent.change(within(columnsPanel).getByLabelText("Column data type"), {
      target: { value: "bigint" },
    });
    fireEvent.click(within(columnsPanel).getByLabelText("Column identity"));

    await waitFor(() =>
      expect(mockCreateTable).toHaveBeenCalledWith(
        expect.objectContaining({
          columns: expect.arrayContaining([
            expect.objectContaining({
              name: "id",
              data_type: "bigint",
              is_identity: true,
            }),
          ]),
        }),
      ),
    );
  });
});
