// Issue #1460 — `supportsDdl(dbType, action)` reads the per-action `ddl.*`
// capability so the four schema-mutation entry points (Create Table / Alter
// Table / Create Index / Drop object) surface only where the wired backend
// adapter can actually execute that DDL. A flag may sit narrower than the
// adapter while a backend slice waits for its UI half. Grounds (adapter code):
//   - PostgreSQL / MySQL / MariaDB / MSSQL / Oracle — every DDL trait method
//     delegates to a real executor → all four true (MSSQL wired by #1071,
//     Oracle by #1072).
//   - SQLite — the narrower case. #1804 wired native drop/rename/column/index
//     and only `add_constraint` / `drop_constraint` still return
//     `sqlite_unsupported(...)`, but the UI half has not landed, so the ledger
//     still claims `createTable` true and the rest false.
//   - DuckDB — #1070 (ADR 0051 Stage 2) wires native structural DDL: table
//     create/drop/rename, column add/drop/type, index create/drop → the four
//     base actions true. `alterConstraint` stays false (DuckDB `ALTER TABLE`
//     cannot add/drop constraints — Stage 2b rebuild-swap).
//   - `alterConstraint` — full-DDL engines (PG/MySQL/MSSQL/Oracle) true; SQLite
//     + DuckDB false (neither can ALTER TABLE ADD/DROP CONSTRAINT).
//   - `identityColumn` — same split: PG emits `GENERATED BY DEFAULT AS
//     IDENTITY`, MySQL `AUTO_INCREMENT`, MSSQL `IDENTITY(1,1)`, Oracle
//     `GENERATED BY DEFAULT AS IDENTITY`; SQLite and DuckDB reject
//     `is_identity` with `Unsupported`, so the Identity checkbox is hidden.
//   - Unknown / still-loading dbType — true for every action (same
//     affordance-preserving fallback as `supportsRowEditing`).
import { describe, expect, it } from "vitest";
import { type DdlCapabilityName, supportsDdl } from "./dataSource";

const ACTIONS: readonly DdlCapabilityName[] = [
  "createTable",
  "alterTable",
  "createIndex",
  "dropObject",
  "alterConstraint",
  "identityColumn",
];

describe("supportsDdl (#1460)", () => {
  it("claims all four DDL actions for PostgreSQL, the MySQL family, MSSQL, and Oracle", () => {
    for (const dbType of [
      "postgresql",
      "mysql",
      "mariadb",
      "mssql",
      "oracle",
    ] as const) {
      for (const action of ACTIONS) {
        expect(supportsDdl(dbType, action)).toBe(true);
      }
    }
  });

  it("claims only createTable for SQLite (adapter wires create_table alone)", () => {
    expect(supportsDdl("sqlite", "createTable")).toBe(true);
    expect(supportsDdl("sqlite", "alterTable")).toBe(false);
    expect(supportsDdl("sqlite", "createIndex")).toBe(false);
    expect(supportsDdl("sqlite", "dropObject")).toBe(false);
    expect(supportsDdl("sqlite", "alterConstraint")).toBe(false);
    // #1070 — `build_column_definition` rejects `is_identity` with
    // `Unsupported`, so the Identity checkbox is hidden for SQLite too.
    expect(supportsDdl("sqlite", "identityColumn")).toBe(false);
  });

  it("claims native structural DDL for DuckDB but not constraints (#1070 Stage 2)", () => {
    expect(supportsDdl("duckdb", "createTable")).toBe(true);
    expect(supportsDdl("duckdb", "alterTable")).toBe(true);
    expect(supportsDdl("duckdb", "createIndex")).toBe(true);
    expect(supportsDdl("duckdb", "dropObject")).toBe(true);
    // Stage 2b — DuckDB ALTER TABLE cannot add/drop constraints (rebuild-swap).
    expect(supportsDdl("duckdb", "alterConstraint")).toBe(false);
    // Stage 2b — DuckDB auto-increment needs CREATE SEQUENCE + DEFAULT
    // nextval(...); the adapter rejects `is_identity` with `Unsupported`.
    expect(supportsDdl("duckdb", "identityColumn")).toBe(false);
  });

  it("returns true for every action while the dbType is unknown / still loading", () => {
    // Issue #1735 — `editColumnComment` rides the same fail-open fallback
    // (`StructurePanel.tsx` reads it before the connection resolves), so it is
    // asserted alongside the four #1460 actions instead of being left out of
    // the `ACTIONS` matrix. It is NOT in `ACTIONS` because the per-engine
    // matrix above expects all listed actions to be true for MySQL/MSSQL.
    for (const action of [...ACTIONS, "editColumnComment" as const]) {
      expect(supportsDdl(null, action)).toBe(true);
      expect(supportsDdl(undefined, action)).toBe(true);
    }
  });

  // Issue #1735 — column comment edit is emit-wired only for PostgreSQL +
  // Oracle (shared ANSI COMMENT ON COLUMN). MySQL/MariaDB and MSSQL run
  // structural ALTER TABLE but have no ANSI COMMENT ON (comment is part of the
  // column definition / an extended property), so the finer-grained
  // `editColumnComment` flag gates the comment-edit affordance separately from
  // `alterTable`. (2026-07-25)
  it("claims editColumnComment only for PostgreSQL and Oracle", () => {
    expect(supportsDdl("postgresql", "editColumnComment")).toBe(true);
    expect(supportsDdl("oracle", "editColumnComment")).toBe(true);
    for (const dbType of [
      "mysql",
      "mariadb",
      "mssql",
      "sqlite",
      "duckdb",
    ] as const) {
      expect(supportsDdl(dbType, "editColumnComment")).toBe(false);
    }
  });
});
