//! MySQL DDL mutations — drop / rename / alter table, index / constraint
//! lifecycle, trigger create/drop. Sprint 284 (Slice D) → 285 (Slice E) →
//! 286 (Slice F triggers).
//!
//! PG (`db/postgres/mutations.rs`) 의 패턴과 동등하되 dialect 차이:
//! - identifier quoting: backtick (PG `"`) + 64-byte 한도.
//! - rename: `RENAME TABLE old TO new` (PG `ALTER TABLE … RENAME TO …`).
//! - DROP TABLE 에 `CASCADE` 키워드 없음 — `req.cascade` 는 의도 보존을
//!   위해 받지만 emission 단계에선 silent ignore.
//! - IDENTITY: MySQL `AUTO_INCREMENT` 키워드 (PG `GENERATED BY DEFAULT AS
//!   IDENTITY`).
//! - DROP COLUMN: CASCADE 키워드 없음 — 동일하게 ignore.
//! - DROP INDEX: `DROP INDEX name ON qualified_table` (PG 는 `DROP INDEX
//!   schema.name`).
//! - DROP CONSTRAINT: MySQL 8.0.19+ 의 `ALTER TABLE … DROP CONSTRAINT name`
//!   으로 통일 (CHECK/UNIQUE/FK 모두 처리, PK 는 별도 `DROP PRIMARY KEY`).
//! - CHECK constraint: MySQL 8.0.16+ 에서 enforced — 그 이전 server 는 SQL
//!   파싱은 받되 무시한다 (호환성 issue 는 server-side 가 surface).
//! - CREATE TRIGGER: MySQL 은 함수 reference 가 없고 trigger body 가 inline
//!   compound statement — 즉 PG `CreateTriggerRequest` 의 `function_name`
//!   필드 의미가 달라 직접 mapping 어렵다. Phase 17 에선 list/source 의
//!   read-only 만 지원하고 create/drop 은 `Unsupported` 로 reject (frontend
//!   dialog 는 paradigm 별 분기로 MySQL 일 때 hide; Sprint 273 master spec).

use sqlx::MySqlPool;
use tracing::info;

use crate::error::AppError;
use crate::models::{
    AddColumnRequest, AddConstraintRequest, AlterTableRequest, ColumnChange, ConstraintDefinition,
    CreateIndexRequest, CreateTableRequest, DropColumnRequest, DropConstraintRequest,
    DropIndexRequest, DropTableRequest, RenameTableRequest, SchemaChangeResult,
};

use super::MysqlAdapter;

/// MySQL 식별자 최대 byte 길이. utf8mb4 기준 server limit (PG 의 `NAMEDATALEN`
/// 63 과 동등 위상).
const MYSQL_IDENTIFIER_MAX_BYTES: usize = 64;

/// PG `validate_identifier` 와 동일 contract — `[a-zA-Z_][a-zA-Z0-9_]*` +
/// length ≤ 64 bytes. NUL / backtick / 공백은 body rule 로 implicit 거부.
/// 사용자 식별자는 quoting 으로 자유로운 문자 허용 가능하나, 본 어댑터는
/// PG 와 동일하게 ASCII-only sub-set 만 인정 — frontend 가 PG/MySQL 공통
/// 검증 메시지를 쓰도록 한다.
pub(super) fn validate_identifier(name: &str, label: &str) -> Result<(), AppError> {
    let trimmed = name.trim();
    if trimmed.is_empty() {
        return Err(AppError::Validation(format!("{} must not be empty", label)));
    }
    if trimmed.len() > MYSQL_IDENTIFIER_MAX_BYTES {
        return Err(AppError::Validation(format!(
            "{} must not exceed {} bytes",
            label, MYSQL_IDENTIFIER_MAX_BYTES
        )));
    }
    let mut chars = trimmed.chars();
    let Some(first) = chars.next() else {
        return Err(AppError::Validation(format!("{} must not be empty", label)));
    };
    if !first.is_ascii_alphabetic() && first != '_' {
        return Err(AppError::Validation(format!(
            "{} must start with a letter or underscore",
            label
        )));
    }
    for ch in chars {
        if !ch.is_ascii_alphanumeric() && ch != '_' {
            return Err(AppError::Validation(format!(
                "{} must contain only alphanumeric characters and underscores",
                label
            )));
        }
    }
    Ok(())
}

/// Backtick 으로 감싸고 literal backtick 은 더블링. queries.rs 의 동명
/// helper 와 동일 — 모듈 간 공유는 `super::queries::quote_ident` import 로.
pub(super) fn quote_ident(name: &str) -> String {
    format!("`{}`", name.replace('`', "``"))
}

/// `schema`.`table` qualified form.
pub(super) fn qualified_table(schema: &str, table: &str) -> String {
    format!("{}.{}", quote_ident(schema), quote_ident(table))
}

/// MySQL referential action whitelist — PG 와 동일 closed set.
const REFERENTIAL_ACTIONS: &[&str] = &[
    "NO ACTION",
    "RESTRICT",
    "CASCADE",
    "SET NULL",
    "SET DEFAULT",
];

fn format_referential_action_clause(
    action: Option<&str>,
    clause: &str,
) -> Result<String, AppError> {
    match action {
        None => Ok(String::new()),
        Some(a) => {
            if REFERENTIAL_ACTIONS.contains(&a) {
                Ok(format!(" {} {}", clause, a))
            } else {
                Err(AppError::Validation(format!(
                    "Invalid referential action: {} (expected one of {})",
                    a,
                    REFERENTIAL_ACTIONS.join(", ")
                )))
            }
        }
    }
}

/// MySQL `CREATE INDEX name USING <type> ON table (...)` 의 type whitelist.
/// InnoDB 는 BTREE 만 효과적이지만 HASH 도 syntax 적으로 받는다 (MEMORY
/// engine 용).
const MYSQL_INDEX_TYPES: &[&str] = &["btree", "hash"];

/// 단일 statement 실행 + transaction wrap. PG 의 `BEGIN/COMMIT` 패턴 답습.
/// 주의: MySQL 의 DDL 은 implicit-commit (transaction 안에서 ALTER TABLE
/// 등을 실행해도 자동 commit) — explicit transaction 이 안전망 역할은
/// 제한적이지만, PG 와 surface 를 맞추고 multi-statement chain 시 best-
/// effort rollback path 를 유지하기 위해 그대로 사용한다.
async fn run_in_tx(pool: &MySqlPool, sql: &str) -> Result<(), AppError> {
    let mut tx = pool
        .begin()
        .await
        .map_err(|e| AppError::Database(e.to_string()))?;
    if let Err(e) = sqlx::query(sql).execute(&mut *tx).await {
        let _ = tx.rollback().await;
        return Err(AppError::Database(e.to_string()));
    }
    tx.commit()
        .await
        .map_err(|e| AppError::Database(format!("commit failed: {}", e)))?;
    Ok(())
}

impl MysqlAdapter {
    pub async fn drop_table(&self, req: &DropTableRequest) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;

        // MySQL DROP TABLE 은 CASCADE 키워드를 받지 않는다. `req.cascade`
        // 는 cross-dialect 의도 보존을 위해 받지만 emission 단계에선 그대로
        // 무시 — InnoDB 의 FK 는 ON DELETE CASCADE 가 schema 정의에 있으므로
        // 사용자 입장에서 의미 손실은 미미. 향후 frontend 가 dialect별로
        // CASCADE 옵션을 hide 하는 polish 는 별 sprint.
        let qualified = qualified_table(&req.schema, &req.table);
        let sql = format!("DROP TABLE {}", qualified);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!("Dropped table {}.{}", req.schema, req.table);
        Ok(SchemaChangeResult { sql })
    }

    pub async fn rename_table(
        &self,
        req: &RenameTableRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.new_name, "New table name")?;

        // MySQL 의 canonical rename 은 `RENAME TABLE old TO new` —
        // `ALTER TABLE … RENAME TO …` 도 동작하지만 `RENAME TABLE` 이 multi-
        // table atomic rename 까지 cover 하는 표준 form.
        let qualified_old = qualified_table(&req.schema, &req.table);
        // 새 이름은 동일 schema 안 — qualified 로 emit 해 모호성 차단.
        let qualified_new = qualified_table(&req.schema, req.new_name.trim());
        let sql = format!("RENAME TABLE {} TO {}", qualified_old, qualified_new);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!(
            "Renamed table {}.{} to {}",
            req.schema,
            req.table,
            req.new_name.trim()
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn add_column(&self, req: &AddColumnRequest) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.column.name, "Column name")?;
        if req.column.data_type.trim().is_empty() {
            return Err(AppError::Validation(format!(
                "Column '{}' must have a non-empty data type",
                req.column.name
            )));
        }

        let qualified = qualified_table(&req.schema, &req.table);
        let mut col_def = format!(
            "{} {}",
            quote_ident(&req.column.name),
            req.column.data_type.trim()
        );
        // MySQL IDENTITY 등가 — `AUTO_INCREMENT` 는 NOT NULL 을 implicit
        // 요구. PG `GENERATED BY DEFAULT AS IDENTITY NOT NULL` 와 동일 의미.
        // AUTO_INCREMENT 컬럼은 PRIMARY KEY 또는 UNIQUE 가 필요한데, PG 와
        // 동일하게 추가 검증은 server 에 위임 (frontend 가 pk_columns 를
        // 함께 보내는 흐름).
        if req.column.is_identity {
            col_def.push_str(" AUTO_INCREMENT NOT NULL");
        } else {
            if !req.column.nullable {
                col_def.push_str(" NOT NULL");
            }
            if let Some(default) = &req.column.default_value {
                let trimmed = default.trim();
                if !trimmed.is_empty() {
                    col_def.push_str(&format!(" DEFAULT {}", trimmed));
                }
            }
        }
        if let Some(raw) = &req.column.comment {
            let trimmed = raw.trim();
            if !trimmed.is_empty() {
                let escaped = trimmed.replace('\'', "''");
                col_def.push_str(&format!(" COMMENT '{}'", escaped));
            }
        }
        if let Some(expr) = &req.check_expression {
            let trimmed = expr.trim();
            if !trimmed.is_empty() {
                col_def.push_str(&format!(" CHECK ({})", trimmed));
            }
        }

        let sql = format!("ALTER TABLE {} ADD COLUMN {}", qualified, col_def);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!(
            "Added column {} on {}.{}",
            req.column.name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn drop_column(
        &self,
        req: &DropColumnRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.column_name, "Column name")?;

        let qualified = qualified_table(&req.schema, &req.table);
        let quoted_col = quote_ident(&req.column_name);
        // MySQL DROP COLUMN 도 CASCADE 키워드 없음 — `req.cascade` 무시.
        let sql = format!("ALTER TABLE {} DROP COLUMN {}", qualified, quoted_col);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!(
            "Dropped column {} from {}.{}",
            req.column_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn create_table(
        &self,
        req: &CreateTableRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.name, "Table name")?;

        if req.columns.is_empty() {
            return Err(AppError::Validation(
                "Table must have at least one column".into(),
            ));
        }

        for col in &req.columns {
            validate_identifier(&col.name, "Column name")?;
            if col.data_type.trim().is_empty() {
                return Err(AppError::Validation(format!(
                    "Column '{}' must have a non-empty data type",
                    col.name
                )));
            }
        }

        if let Some(pk_cols) = &req.primary_key {
            for pk in pk_cols {
                validate_identifier(pk, "Primary key column name")?;
                if !req.columns.iter().any(|c| c.name == *pk) {
                    return Err(AppError::Validation(format!(
                        "Primary key column '{}' is not declared in the column list",
                        pk
                    )));
                }
            }
        }

        let qualified = qualified_table(&req.schema, &req.name);

        let mut col_defs: Vec<String> = Vec::with_capacity(req.columns.len() + 1);
        for col in &req.columns {
            let mut def = format!("{} {}", quote_ident(&col.name), col.data_type.trim());
            if col.is_identity {
                def.push_str(" AUTO_INCREMENT NOT NULL");
            } else {
                if !col.nullable {
                    def.push_str(" NOT NULL");
                }
                if let Some(default) = &col.default_value {
                    let trimmed = default.trim();
                    if !trimmed.is_empty() {
                        def.push_str(&format!(" DEFAULT {}", trimmed));
                    }
                }
            }
            // MySQL 의 column comment 는 column 정의 안에 inline (PG 는 별도
            // `COMMENT ON COLUMN` 문). 따로 atomic chain 이 필요 없다.
            if let Some(raw) = &col.comment {
                let trimmed = raw.trim();
                if !trimmed.is_empty() {
                    let escaped = trimmed.replace('\'', "''");
                    def.push_str(&format!(" COMMENT '{}'", escaped));
                }
            }
            col_defs.push(def);
        }

        if let Some(pk_cols) = &req.primary_key {
            if !pk_cols.is_empty() {
                let quoted: Vec<String> = pk_cols.iter().map(|c| quote_ident(c)).collect();
                col_defs.push(format!("PRIMARY KEY ({})", quoted.join(", ")));
            }
        }

        // Engine/charset suffix 는 server default (InnoDB / utf8mb4 권장)
        // 에 위임 — 사용자가 default 외 engine 을 원하면 raw SQL 사용.
        let mut create_sql = format!("CREATE TABLE {} ({})", qualified, col_defs.join(", "));

        // Table-level COMMENT 는 CREATE TABLE 옵션으로 inline 가능 — `(cols)
        //  COMMENT = '…'` 형식. PG 의 `COMMENT ON TABLE` 별도 문과 효과 동등.
        if let Some(raw) = &req.table_comment {
            let trimmed = raw.trim();
            if !trimmed.is_empty() {
                let escaped = trimmed.replace('\'', "''");
                create_sql.push_str(&format!(" COMMENT = '{}'", escaped));
            }
        }

        if req.preview_only {
            return Ok(SchemaChangeResult { sql: create_sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &create_sql).await?;
        info!("Created table {}.{}", req.schema, req.name);
        Ok(SchemaChangeResult { sql: create_sql })
    }

    pub async fn alter_table(
        &self,
        req: &AlterTableRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;

        if req.changes.is_empty() {
            return Err(AppError::Validation(
                "At least one column change is required".into(),
            ));
        }

        for change in &req.changes {
            match change {
                ColumnChange::Add { name, .. } => validate_identifier(name, "Column name")?,
                ColumnChange::Modify {
                    name,
                    new_data_type,
                    using_expression,
                    ..
                } => {
                    validate_identifier(name, "Column name")?;
                    if new_data_type.is_none() && using_expression.is_some() {
                        return Err(AppError::Validation(
                            "USING expression requires a new data type (MySQL ignores USING — use raw SQL for casts)".into(),
                        ));
                    }
                }
                ColumnChange::Drop { name } => validate_identifier(name, "Column name")?,
            }
        }

        let qualified = qualified_table(&req.schema, &req.table);
        let mut parts: Vec<String> = Vec::new();

        for change in &req.changes {
            match change {
                ColumnChange::Add {
                    name,
                    data_type,
                    nullable,
                    default_value,
                } => {
                    let mut sql = format!("ADD COLUMN {} {}", quote_ident(name), data_type);
                    if !nullable {
                        sql.push_str(" NOT NULL");
                    }
                    if let Some(default) = default_value {
                        sql.push_str(&format!(" DEFAULT {}", default));
                    }
                    parts.push(sql);
                }
                ColumnChange::Modify {
                    name,
                    new_data_type,
                    new_nullable,
                    new_default_value,
                    using_expression: _,
                } => {
                    // MySQL 의 modify column 은 PG 처럼 type/nullable/default
                    // 를 분리 절로 못 보낸다 — 전체 column 정의를 다시 쓰는
                    // `MODIFY COLUMN col <type> [NOT NULL] [DEFAULT v]` 형식.
                    // new_data_type 이 None 이면 fallback 으로 `'KEEP TYPE'`
                    // 같은 마커를 만들 수 없으므로 명시 reject 한다 — caller
                    // 는 frontend 측에서 항상 type 을 같이 보낸다.
                    let quoted_name = quote_ident(name);
                    let Some(dt) = new_data_type else {
                        return Err(AppError::Validation(format!(
                            "MySQL MODIFY COLUMN requires a data type for '{}'",
                            name
                        )));
                    };
                    let mut sql = format!("MODIFY COLUMN {} {}", quoted_name, dt);
                    if let Some(nullable) = new_nullable {
                        sql.push_str(if *nullable { " NULL" } else { " NOT NULL" });
                    }
                    if let Some(default) = new_default_value {
                        sql.push_str(&format!(" DEFAULT {}", default));
                    }
                    parts.push(sql);
                }
                ColumnChange::Drop { name } => {
                    parts.push(format!("DROP COLUMN {}", quote_ident(name)));
                }
            }
        }

        let sql = format!("ALTER TABLE {} {}", qualified, parts.join(", "));

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!("Altered table {}.{}", req.schema, req.table);
        Ok(SchemaChangeResult { sql })
    }

    pub async fn create_index(
        &self,
        req: &CreateIndexRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.index_name, "Index name")?;

        if req.columns.is_empty() {
            return Err(AppError::Validation(
                "At least one column is required for an index".into(),
            ));
        }
        for col in &req.columns {
            validate_identifier(col, "Index column name")?;
        }

        let index_type_lower = req.index_type.to_lowercase();
        if !MYSQL_INDEX_TYPES.contains(&index_type_lower.as_str()) {
            return Err(AppError::Validation(format!(
                "Index type must be one of: {}",
                MYSQL_INDEX_TYPES.join(", ")
            )));
        }

        let qualified = qualified_table(&req.schema, &req.table);
        let columns: Vec<String> = req.columns.iter().map(|c| quote_ident(c)).collect();

        let unique = if req.is_unique { "UNIQUE " } else { "" };
        let sql = format!(
            "CREATE {}INDEX {} USING {} ON {} ({})",
            unique,
            quote_ident(&req.index_name),
            index_type_lower.to_uppercase(),
            qualified,
            columns.join(", ")
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!(
            "Created index {} on {}.{}",
            req.index_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn drop_index(&self, req: &DropIndexRequest) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.index_name, "Index name")?;
        // MySQL DROP INDEX 는 `ON <table>` 이 필요하다. PG 호출자는 table 을
        // 생략해도 되지만, MySQL adapter 는 schema-only request 를 명시적
        // validation 오류로 거부해 frontend payload 누락을 조용히 삼키지 않는다.
        if req.table.trim().is_empty() {
            return Err(AppError::Validation(
                "MySQL DROP INDEX requires a table — request.table must not be empty".into(),
            ));
        }
        validate_identifier(&req.table, "Table name")?;
        let qualified = qualified_table(&req.schema, &req.table);
        // MySQL 의 IF EXISTS 는 8.0.13+ 에서 지원. 미지원 server 는 syntax
        // error 가 surface — frontend 의 옵션 toggle 로 OFF 권장.
        let if_exists = if req.if_exists { "IF EXISTS " } else { "" };
        let sql = format!(
            "DROP INDEX {}{} ON {}",
            if_exists,
            quote_ident(&req.index_name),
            qualified
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!("Dropped index {}.{}", req.schema, req.index_name);
        Ok(SchemaChangeResult { sql })
    }

    pub async fn add_constraint(
        &self,
        req: &AddConstraintRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.constraint_name, "Constraint name")?;

        let qualified = qualified_table(&req.schema, &req.table);
        let constraint_name = quote_ident(&req.constraint_name);

        let constraint_sql = match &req.definition {
            ConstraintDefinition::PrimaryKey { columns } => {
                if columns.is_empty() {
                    return Err(AppError::Validation(
                        "Primary key requires at least one column".into(),
                    ));
                }
                for col in columns {
                    validate_identifier(col, "Primary key column name")?;
                }
                let cols: Vec<String> = columns.iter().map(|c| quote_ident(c)).collect();
                // MySQL PRIMARY KEY 는 named constraint 안 됨 — 이름이 무시
                // 된다. `ADD CONSTRAINT name PRIMARY KEY` 도 syntax 적으론
                // 받지만 name 부분만 silent drop. emit 은 동일 form 유지.
                format!("PRIMARY KEY ({})", cols.join(", "))
            }
            ConstraintDefinition::ForeignKey {
                columns,
                reference_table,
                reference_columns,
                on_delete,
                on_update,
            } => {
                if columns.is_empty() {
                    return Err(AppError::Validation(
                        "Foreign key requires at least one column".into(),
                    ));
                }
                for col in columns {
                    validate_identifier(col, "Foreign key column name")?;
                }
                validate_identifier(reference_table, "Foreign key reference table name")?;
                for col in reference_columns {
                    validate_identifier(col, "Foreign key reference column name")?;
                }
                let cols: Vec<String> = columns.iter().map(|c| quote_ident(c)).collect();
                let ref_cols: Vec<String> =
                    reference_columns.iter().map(|c| quote_ident(c)).collect();
                let on_delete_clause =
                    format_referential_action_clause(on_delete.as_deref(), "ON DELETE")?;
                let on_update_clause =
                    format_referential_action_clause(on_update.as_deref(), "ON UPDATE")?;
                // MySQL FK 는 reference_table 만 받고 schema 는 implicit
                // (또는 `db.table` 형식). 본 emitter 는 schema 자유롭게
                // qualify 하지 않고 PG 와 동일하게 table-only 로 emit —
                // cross-schema FK 는 raw SQL 권장.
                format!(
                    "FOREIGN KEY ({}) REFERENCES {} ({}){}{}",
                    cols.join(", "),
                    quote_ident(reference_table),
                    ref_cols.join(", "),
                    on_delete_clause,
                    on_update_clause,
                )
            }
            ConstraintDefinition::Unique { columns } => {
                if columns.is_empty() {
                    return Err(AppError::Validation(
                        "Unique constraint requires at least one column".into(),
                    ));
                }
                for col in columns {
                    validate_identifier(col, "Unique constraint column name")?;
                }
                let cols: Vec<String> = columns.iter().map(|c| quote_ident(c)).collect();
                format!("UNIQUE ({})", cols.join(", "))
            }
            ConstraintDefinition::Check { expression } => {
                if expression.trim().is_empty() {
                    return Err(AppError::Validation(
                        "Check constraint expression must not be empty".into(),
                    ));
                }
                // MySQL 8.0.16+ 에서 CHECK enforced. 그 이전 server 는 SQL
                // 을 parse 받되 무시 — server 가 surface 하는 호환성 문제.
                format!("CHECK ({})", expression)
            }
        };

        let sql = format!(
            "ALTER TABLE {} ADD CONSTRAINT {} {}",
            qualified, constraint_name, constraint_sql
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!(
            "Added constraint {} on {}.{}",
            req.constraint_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn drop_constraint(
        &self,
        req: &DropConstraintRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.constraint_name, "Constraint name")?;

        let qualified = qualified_table(&req.schema, &req.table);
        // MySQL 8.0.19+ 의 unified `DROP CONSTRAINT name` 사용 — CHECK /
        // UNIQUE / FK 모두 처리. PK 의 명시적 `DROP PRIMARY KEY` 는 본
        // unified syntax 가 lookup table 로 알아낸다.
        let sql = format!(
            "ALTER TABLE {} DROP CONSTRAINT {}",
            qualified,
            quote_ident(&req.constraint_name)
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!(
            "Dropped constraint {} from {}.{}",
            req.constraint_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }
}

#[cfg(test)]
mod tests {
    //! 작성 이유 (2026-05-13, Sprint 284-285): SQL emission 은 pure (pool 없
    //! 이도 build) — preview_only=true path 로 byte-equivalent 회귀 가드.
    //! identifier 검증, MySQL dialect 특유의 emission 차이 (RENAME TABLE,
    //! AUTO_INCREMENT, MODIFY COLUMN, DROP INDEX … ON …) 가 회귀하면 frontend
    //! preview 의 사용자 surface 가 깨지므로 우선 가드.
    use super::*;
    use crate::models::{
        AddColumnRequest, AddConstraintRequest, AlterTableRequest, ColumnChange, ColumnDefinition,
        ConstraintDefinition, CreateIndexRequest, CreateTableRequest, DropColumnRequest,
        DropConstraintRequest, DropIndexRequest, DropTableRequest, RenameTableRequest,
    };

    fn drop_req(schema: &str, table: &str) -> DropTableRequest {
        DropTableRequest {
            connection_id: "c".into(),
            schema: schema.into(),
            table: table.into(),
            cascade: false,
            preview_only: true,
            expected_database: None,
        }
    }

    fn rename_req(schema: &str, table: &str, new_name: &str) -> RenameTableRequest {
        RenameTableRequest {
            connection_id: "c".into(),
            schema: schema.into(),
            table: table.into(),
            new_name: new_name.into(),
            preview_only: true,
            expected_database: None,
        }
    }

    #[test]
    fn validate_identifier_rejects_empty_and_special_chars() {
        assert!(validate_identifier("", "Col").is_err());
        assert!(validate_identifier("   ", "Col").is_err());
        assert!(validate_identifier("1abc", "Col").is_err());
        assert!(validate_identifier("a-b", "Col").is_err());
        assert!(validate_identifier("a b", "Col").is_err());
        assert!(validate_identifier("a`b", "Col").is_err());
        assert!(validate_identifier("a\"b", "Col").is_err());
    }

    #[test]
    fn validate_identifier_accepts_ascii_underscore_alnum() {
        assert!(validate_identifier("users", "T").is_ok());
        assert!(validate_identifier("_priv", "T").is_ok());
        assert!(validate_identifier("col_1", "T").is_ok());
    }

    #[test]
    fn validate_identifier_enforces_64_byte_limit() {
        // 65-byte name — MySQL 한계 초과.
        let long = "a".repeat(65);
        let err = validate_identifier(&long, "Col").unwrap_err();
        assert!(format!("{err}").contains("64"));
        // 정확히 64-byte 는 통과.
        let ok = "a".repeat(64);
        assert!(validate_identifier(&ok, "Col").is_ok());
    }

    #[test]
    fn quote_ident_doubles_backticks() {
        assert_eq!(quote_ident("users"), "`users`");
        assert_eq!(quote_ident("we`ird"), "`we``ird`");
    }

    #[tokio::test]
    async fn drop_table_preview_emits_simple_form() {
        let a = MysqlAdapter::new();
        let req = drop_req("app", "users");
        let r = a.drop_table(&req).await.unwrap();
        assert_eq!(r.sql, "DROP TABLE `app`.`users`");
    }

    #[tokio::test]
    async fn drop_table_preview_ignores_cascade_flag() {
        let a = MysqlAdapter::new();
        let mut req = drop_req("app", "users");
        req.cascade = true;
        let r = a.drop_table(&req).await.unwrap();
        // MySQL 은 CASCADE 키워드 없음 — emission 동일.
        assert_eq!(r.sql, "DROP TABLE `app`.`users`");
    }

    #[tokio::test]
    async fn rename_table_preview_uses_rename_table_syntax() {
        let a = MysqlAdapter::new();
        let req = rename_req("app", "users", "people");
        let r = a.rename_table(&req).await.unwrap();
        assert_eq!(r.sql, "RENAME TABLE `app`.`users` TO `app`.`people`");
    }

    #[tokio::test]
    async fn add_column_preview_emits_identity_as_auto_increment() {
        let a = MysqlAdapter::new();
        let req = AddColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column: ColumnDefinition {
                name: "id".into(),
                data_type: "BIGINT".into(),
                nullable: true,
                default_value: None,
                is_identity: true,
                comment: None,
            },
            check_expression: None,
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_column(&req).await.unwrap();
        assert!(
            r.sql.contains("AUTO_INCREMENT NOT NULL"),
            "expected AUTO_INCREMENT NOT NULL emission: {}",
            r.sql
        );
        assert!(r.sql.contains("ALTER TABLE `app`.`users`"));
    }

    #[tokio::test]
    async fn add_column_preview_emits_check_clause() {
        let a = MysqlAdapter::new();
        let req = AddColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column: ColumnDefinition {
                name: "age".into(),
                data_type: "INT".into(),
                nullable: false,
                default_value: None,
                is_identity: false,
                comment: None,
            },
            check_expression: Some("age >= 0".into()),
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_column(&req).await.unwrap();
        assert!(
            r.sql.ends_with("CHECK (age >= 0)"),
            "expected trailing CHECK: {}",
            r.sql
        );
    }

    #[tokio::test]
    async fn drop_column_preview_no_cascade_keyword() {
        let a = MysqlAdapter::new();
        let req = DropColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column_name: "deprecated".into(),
            cascade: true,
            preview_only: true,
            expected_database: None,
        };
        let r = a.drop_column(&req).await.unwrap();
        // cascade=true 라도 MySQL 은 CASCADE 키워드 없음.
        assert_eq!(r.sql, "ALTER TABLE `app`.`users` DROP COLUMN `deprecated`");
    }

    #[tokio::test]
    async fn create_table_preview_emits_columns_pk_and_comments() {
        let a = MysqlAdapter::new();
        let req = CreateTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            name: "users".into(),
            columns: vec![
                ColumnDefinition {
                    name: "id".into(),
                    data_type: "BIGINT".into(),
                    nullable: false,
                    default_value: None,
                    is_identity: true,
                    comment: Some("PK".into()),
                },
                ColumnDefinition {
                    name: "name".into(),
                    data_type: "VARCHAR(120)".into(),
                    nullable: false,
                    default_value: Some("'anon'".into()),
                    is_identity: false,
                    comment: None,
                },
            ],
            primary_key: Some(vec!["id".into()]),
            table_comment: Some("user records".into()),
            preview_only: true,
            expected_database: None,
        };
        let r = a.create_table(&req).await.unwrap();
        assert!(r.sql.starts_with("CREATE TABLE `app`.`users` ("));
        assert!(r
            .sql
            .contains("`id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'PK'"));
        assert!(r
            .sql
            .contains("`name` VARCHAR(120) NOT NULL DEFAULT 'anon'"));
        assert!(r.sql.contains("PRIMARY KEY (`id`)"));
        assert!(r.sql.ends_with("COMMENT = 'user records'"));
    }

    #[tokio::test]
    async fn alter_table_preview_modify_requires_data_type() {
        let a = MysqlAdapter::new();
        let req = AlterTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            changes: vec![ColumnChange::Modify {
                name: "age".into(),
                new_data_type: None,
                new_nullable: Some(true),
                new_default_value: None,
                using_expression: None,
            }],
            preview_only: true,
            expected_database: None,
        };
        let err = a.alter_table(&req).await.unwrap_err();
        assert!(format!("{err}").contains("data type"));
    }

    #[tokio::test]
    async fn alter_table_preview_modify_emits_modify_column() {
        let a = MysqlAdapter::new();
        let req = AlterTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            changes: vec![ColumnChange::Modify {
                name: "age".into(),
                new_data_type: Some("BIGINT".into()),
                new_nullable: Some(false),
                new_default_value: Some("0".into()),
                using_expression: None,
            }],
            preview_only: true,
            expected_database: None,
        };
        let r = a.alter_table(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`users` MODIFY COLUMN `age` BIGINT NOT NULL DEFAULT 0"
        );
    }

    #[tokio::test]
    async fn create_index_preview_btree_unique() {
        let a = MysqlAdapter::new();
        let req = CreateIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            index_name: "idx_users_email".into(),
            columns: vec!["email".into()],
            is_unique: true,
            index_type: "btree".into(),
            preview_only: true,
            expected_database: None,
        };
        let r = a.create_index(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "CREATE UNIQUE INDEX `idx_users_email` USING BTREE ON `app`.`users` (`email`)"
        );
    }

    #[tokio::test]
    async fn create_index_rejects_unknown_type() {
        let a = MysqlAdapter::new();
        let req = CreateIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            index_name: "i".into(),
            columns: vec!["email".into()],
            is_unique: false,
            index_type: "gin".into(),
            preview_only: true,
            expected_database: None,
        };
        let err = a.create_index(&req).await.unwrap_err();
        assert!(format!("{err}").to_lowercase().contains("btree"));
    }

    #[tokio::test]
    async fn drop_index_preview_emits_on_table() {
        let a = MysqlAdapter::new();
        let req = DropIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            index_name: "idx_x".into(),
            if_exists: true,
            preview_only: true,
            expected_database: None,
        };
        let r = a.drop_index(&req).await.unwrap();
        assert_eq!(r.sql, "DROP INDEX IF EXISTS `idx_x` ON `app`.`users`");
    }

    #[tokio::test]
    async fn drop_index_requires_table() {
        let a = MysqlAdapter::new();
        let req = DropIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "".into(),
            index_name: "idx_x".into(),
            if_exists: false,
            preview_only: true,
            expected_database: None,
        };
        let err = a.drop_index(&req).await.unwrap_err();
        assert!(format!("{err}").contains("table"));
    }

    #[tokio::test]
    async fn add_constraint_check_preview() {
        let a = MysqlAdapter::new();
        let req = AddConstraintRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            constraint_name: "chk_age".into(),
            definition: ConstraintDefinition::Check {
                expression: "age >= 0".into(),
            },
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_constraint(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`users` ADD CONSTRAINT `chk_age` CHECK (age >= 0)"
        );
    }

    #[tokio::test]
    async fn add_constraint_fk_with_actions() {
        let a = MysqlAdapter::new();
        let req = AddConstraintRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "orders".into(),
            constraint_name: "fk_user".into(),
            definition: ConstraintDefinition::ForeignKey {
                columns: vec!["user_id".into()],
                reference_table: "users".into(),
                reference_columns: vec!["id".into()],
                on_delete: Some("CASCADE".into()),
                on_update: Some("RESTRICT".into()),
            },
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_constraint(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`orders` ADD CONSTRAINT `fk_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT"
        );
    }

    #[tokio::test]
    async fn drop_constraint_preview_uses_unified_syntax() {
        let a = MysqlAdapter::new();
        let req = DropConstraintRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "orders".into(),
            constraint_name: "fk_user".into(),
            preview_only: true,
            expected_database: None,
        };
        let r = a.drop_constraint(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`orders` DROP CONSTRAINT `fk_user`"
        );
    }
}
