import type { IndexDraft } from "./IndexesTabBody";
import type {
  ForeignKeyDraft,
  CheckDraft,
  UniqueDraft,
} from "./ForeignKeysTabBody";

export type TabKey = "columns" | "keys" | "indexes" | "foreign_keys";

export interface ColumnDraft {
  trackingId: string;
  name: string;
  data_type: string;
  nullable: boolean;
  default_value: string;
  comment: string;
  is_pk: boolean;
  /**
   * Inline single-column FK target (TablePlus parity). Empty
   * `fk_ref_table` ⇒ no inline FK on this column. When populated, the
   * chain builder synthesises a `ConstraintDefinition::ForeignKey` with a
   * single-element `columns` array and auto-name `fk_<table>_<column>`.
   * Multi-column FKs stay in the Constraints tab.
   *
   * `fk_ref_schema` blank ⇒ fall back to the table's own schema (PG
   * implicit-search-path semantics). `fk_on_delete` / `fk_on_update`
   * default to `"NO ACTION"`; user can override via the cell popover.
   */
  fk_ref_schema: string;
  fk_ref_table: string;
  fk_ref_column: string;
  fk_on_delete: string;
  fk_on_update: string;
  /**
   * Inline single-column CHECK expression. Empty ⇒ no inline CHECK. When
   * non-empty, the chain builder synthesises a `ConstraintDefinition::Check`
   * with auto-name `chk_<table>_<column>`. Multi-column / cross-column
   * CHECKs stay in the Constraints tab.
   */
  check_expression: string;
  /**
   * Identity / auto-increment toggle. When `true` the emitted column gets
   * `GENERATED BY DEFAULT AS IDENTITY` (PG 10+) and the dialog disables the
   * `Nullable` + `default value` inputs (the IDENTITY sequence is the
   * default; PG forces NOT NULL). Caller is still responsible for choosing
   * an integer-family `data_type` (`smallint` / `integer` / `bigint`).
   */
  is_identity: boolean;
}

export function makeId(): string {
  return typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID()
    : Math.random().toString(36).slice(2);
}

export function newDraft(): ColumnDraft {
  return {
    trackingId: makeId(),
    name: "",
    data_type: "",
    nullable: true,
    default_value: "",
    comment: "",
    is_pk: false,
    fk_ref_schema: "",
    fk_ref_table: "",
    fk_ref_column: "",
    fk_on_delete: "NO ACTION",
    fk_on_update: "NO ACTION",
    check_expression: "",
    is_identity: false,
  };
}

export function newIndexDraft(): IndexDraft {
  return {
    trackingId: makeId(),
    name: "",
    columns: [],
    index_type: "btree",
    unique: false,
  };
}

export function newFkDraft(defaultRefSchema: string): ForeignKeyDraft {
  return {
    trackingId: makeId(),
    name: "",
    columns: [],
    ref_schema: defaultRefSchema,
    ref_table: "",
    ref_columns: [],
    on_delete: "NO ACTION",
    on_update: "NO ACTION",
  };
}

export function newCheckDraft(): CheckDraft {
  return {
    trackingId: makeId(),
    name: "",
    expression: "",
  };
}

export function newUniqueDraft(): UniqueDraft {
  return {
    trackingId: makeId(),
    name: "",
    columns: [],
  };
}

/**
 * True iff the index row's `columns` array (in declared order) is exactly
 * the declared PK column array. PG implicitly indexes PK columns with the
 * same shape, so the chain skips the redundant `tauri.createIndex` call
 * (the backend would otherwise succeed, but we'd be paying for a duplicate
 * index — DataGrip parity).
 */
export function indexMatchesPk(idx: IndexDraft, pk: string[]): boolean {
  if (pk.length === 0) return false;
  if (idx.columns.length !== pk.length) return false;
  for (let i = 0; i < pk.length; i += 1) {
    if (idx.columns[i] !== pk[i]) return false;
  }
  return true;
}

/**
 * Generic in-place swap helper for row reorders. Returns the previous list
 * reference unchanged when the move would be a no-op (target tracking id
 * missing, or swap target out of bounds). Preserves React `trackingId`-keyed
 * identity so the swapped rows reuse their existing component instances +
 * DOM nodes.
 */
export function moveByTrackingId<T extends { trackingId: string }>(
  list: T[],
  trackingId: string,
  direction: -1 | 1,
): T[] {
  const idx = list.findIndex((row) => row.trackingId === trackingId);
  if (idx < 0) return list;
  const swap = idx + direction;
  if (swap < 0 || swap >= list.length) return list;
  const next = [...list];
  [next[idx], next[swap]] = [next[swap]!, next[idx]!];
  return next;
}
