//! MySQL DDL mutations — drop / rename / alter table, index / constraint
//! lifecycle, trigger create/drop.
//!
//! Same pattern as PG (`db/postgres/mutations.rs`), with these dialect
//! differences:
//! - identifier quoting: backtick (PG `"`) + a 64-byte limit.
//! - rename: `RENAME TABLE old TO new` (PG `ALTER TABLE … RENAME TO …`).
//! - DROP TABLE takes no `CASCADE` keyword — `req.cascade` is accepted to
//!   preserve intent but silently ignored at emission.
//! - IDENTITY: MySQL `AUTO_INCREMENT` keyword (PG `GENERATED BY DEFAULT AS
//!   IDENTITY`).
//! - DROP COLUMN: no CASCADE keyword — ignored the same way.
//! - DROP INDEX: `DROP INDEX name ON qualified_table` (PG uses `DROP INDEX
//!   schema.name`).
//! - DROP CONSTRAINT: unified on MySQL 8.0.19+'s `ALTER TABLE … DROP
//!   CONSTRAINT name` (handles CHECK/UNIQUE/FK; PK keeps its own `DROP
//!   PRIMARY KEY`).
//! - CHECK constraint: enforced from MySQL 8.0.16+ — older servers parse the
//!   SQL but ignore it (the server surfaces the compatibility issue).
//! - CREATE TRIGGER: MySQL has no function reference and a trigger body is an
//!   inline compound statement, so PG `CreateTriggerRequest`'s
//!   `function_name` field carries a different meaning and does not map
//!   directly. Only the read-only list/source paths are supported; create and
//!   drop are rejected with `Unsupported` (the frontend dialog branches per
//!   paradigm and hides them for MySQL).

use sqlx::MySqlPool;
use tracing::info;

use crate::db::ddl_fragment::validate_ddl_fragment;
use crate::error::AppError;
use crate::models::{
    AddColumnRequest, AddConstraintRequest, AlterTableRequest, ColumnChange, ConstraintDefinition,
    CreateIndexRequest, CreateTableRequest, DropColumnRequest, DropConstraintRequest,
    DropIndexRequest, DropTableRequest, RenameTableRequest, SchemaChangeResult,
};

use super::MysqlAdapter;

/// Maximum MySQL identifier length in bytes — the server limit under utf8mb4
/// (the counterpart of PG's `NAMEDATALEN` 63).
const MYSQL_IDENTIFIER_MAX_BYTES: usize = 64;

/// Same contract as PG's `validate_identifier` — `[a-zA-Z_][a-zA-Z0-9_]*` +
/// length ≤ 64 bytes. NUL / backtick / whitespace are rejected implicitly by
/// the body rule. Quoting could let user identifiers carry arbitrary
/// characters, but this adapter accepts only the ASCII-only subset like PG,
/// so the frontend can use one validation message for both.
pub(super) fn validate_identifier(name: &str, label: &str) -> Result<(), AppError> {
    let trimmed = name.trim();
    if trimmed.is_empty() {
        return Err(AppError::Validation(format!("{} must not be empty", label)));
    }
    if trimmed.len() > MYSQL_IDENTIFIER_MAX_BYTES {
        return Err(AppError::Validation(format!(
            "{} must not exceed {} bytes",
            label, MYSQL_IDENTIFIER_MAX_BYTES
        )));
    }
    let mut chars = trimmed.chars();
    let Some(first) = chars.next() else {
        return Err(AppError::Validation(format!("{} must not be empty", label)));
    };
    if !first.is_ascii_alphabetic() && first != '_' {
        return Err(AppError::Validation(format!(
            "{} must start with a letter or underscore",
            label
        )));
    }
    for ch in chars {
        if !ch.is_ascii_alphanumeric() && ch != '_' {
            return Err(AppError::Validation(format!(
                "{} must contain only alphanumeric characters and underscores",
                label
            )));
        }
    }
    Ok(())
}

/// Wraps in backticks and doubles any literal backtick. Same as the
/// identically named helper in queries.rs — share it across modules by
/// importing `super::queries::quote_ident`.
pub(super) fn quote_ident(name: &str) -> String {
    format!("`{}`", name.replace('`', "``"))
}

/// `schema`.`table` qualified form.
pub(super) fn qualified_table(schema: &str, table: &str) -> String {
    format!("{}.{}", quote_ident(schema), quote_ident(table))
}

/// MySQL string-literal body escaping. In the default SQL mode
/// (`NO_BACKSLASH_ESCAPES` off) both `'` and `\` are escape characters —
/// doubling the backslash first and the quote second is what stops a value
/// like `C:\data\` from escaping the closing quote and breaking the literal.
/// Used when wrapping user strings such as COMMENT in `'…'`.
pub(super) fn escape_string_literal(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "''")
}

/// MySQL referential action whitelist — the same closed set as PG.
const REFERENTIAL_ACTIONS: &[&str] = &[
    "NO ACTION",
    "RESTRICT",
    "CASCADE",
    "SET NULL",
    "SET DEFAULT",
];

fn format_referential_action_clause(
    action: Option<&str>,
    clause: &str,
) -> Result<String, AppError> {
    match action {
        None => Ok(String::new()),
        Some(a) => {
            if REFERENTIAL_ACTIONS.contains(&a) {
                Ok(format!(" {} {}", clause, a))
            } else {
                Err(AppError::Validation(format!(
                    "Invalid referential action: {} (expected one of {})",
                    a,
                    REFERENTIAL_ACTIONS.join(", ")
                )))
            }
        }
    }
}

/// Type whitelist for MySQL `CREATE INDEX name USING <type> ON table (...)`.
/// Only BTREE is effective on InnoDB, but HASH is accepted syntactically (for
/// the MEMORY engine).
const MYSQL_INDEX_TYPES: &[&str] = &["btree", "hash"];

/// Runs a single statement wrapped in a transaction, following PG's
/// `BEGIN/COMMIT` pattern. Note that MySQL DDL implicit-commits (running
/// ALTER TABLE and the like inside a transaction commits anyway), so the
/// explicit transaction is a limited safety net; it stays to keep the surface
/// aligned with PG and to keep a best-effort rollback path for
/// multi-statement chains.
async fn run_in_tx(pool: &MySqlPool, sql: &str) -> Result<(), AppError> {
    let mut tx = pool
        .begin()
        .await
        .map_err(|e| AppError::Database(e.to_string()))?;
    if let Err(e) = sqlx::query(sql).execute(&mut *tx).await {
        let _ = tx.rollback().await;
        return Err(AppError::Database(e.to_string()));
    }
    tx.commit()
        .await
        .map_err(|e| AppError::Database(format!("commit failed: {}", e)))?;
    Ok(())
}

impl MysqlAdapter {
    pub async fn drop_table(&self, req: &DropTableRequest) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;

        // MySQL DROP TABLE takes no CASCADE keyword. `req.cascade` is
        // accepted to preserve cross-dialect intent but ignored at emission —
        // InnoDB keeps ON DELETE CASCADE in the schema definition, so users
        // lose little meaning.
        let qualified = qualified_table(&req.schema, &req.table);
        let sql = format!("DROP TABLE {}", qualified);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!("Dropped table {}.{}", req.schema, req.table);
        Ok(SchemaChangeResult { sql })
    }

    pub async fn rename_table(
        &self,
        req: &RenameTableRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.new_name, "New table name")?;

        // MySQL's canonical rename is `RENAME TABLE old TO new` —
        // `ALTER TABLE … RENAME TO …` also works, but `RENAME TABLE` is the
        // standard form that also covers multi-table atomic rename.
        let qualified_old = qualified_table(&req.schema, &req.table);
        // The new name stays in the same schema — emit it qualified to rule
        // out ambiguity.
        let qualified_new = qualified_table(&req.schema, req.new_name.trim());
        let sql = format!("RENAME TABLE {} TO {}", qualified_old, qualified_new);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!(
            "Renamed table {}.{} to {}",
            req.schema,
            req.table,
            req.new_name.trim()
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn add_column(&self, req: &AddColumnRequest) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.column.name, "Column name")?;
        if req.column.data_type.trim().is_empty() {
            return Err(AppError::Validation(format!(
                "Column '{}' must have a non-empty data type",
                req.column.name
            )));
        }
        validate_ddl_fragment(&req.column.data_type, "Data type")?;
        if let Some(default) = &req.column.default_value {
            validate_ddl_fragment(default, "DEFAULT value")?;
        }

        let qualified = qualified_table(&req.schema, &req.table);
        let mut col_def = format!(
            "{} {}",
            quote_ident(&req.column.name),
            req.column.data_type.trim()
        );
        // MySQL's IDENTITY equivalent — `AUTO_INCREMENT` implicitly requires
        // NOT NULL, which means the same as PG `GENERATED BY DEFAULT AS
        // IDENTITY NOT NULL`. An AUTO_INCREMENT column needs a PRIMARY KEY or
        // UNIQUE, and that extra check is left to the server as in PG (the
        // frontend sends pk_columns along).
        if req.column.is_identity {
            col_def.push_str(" AUTO_INCREMENT NOT NULL");
        } else {
            if !req.column.nullable {
                col_def.push_str(" NOT NULL");
            }
            if let Some(default) = &req.column.default_value {
                let trimmed = default.trim();
                if !trimmed.is_empty() {
                    col_def.push_str(&format!(" DEFAULT {}", trimmed));
                }
            }
        }
        if let Some(raw) = &req.column.comment {
            let trimmed = raw.trim();
            if !trimmed.is_empty() {
                let escaped = escape_string_literal(trimmed);
                col_def.push_str(&format!(" COMMENT '{}'", escaped));
            }
        }
        if let Some(expr) = &req.check_expression {
            let trimmed = expr.trim();
            if !trimmed.is_empty() {
                validate_ddl_fragment(trimmed, "Check expression")?;
                col_def.push_str(&format!(" CHECK ({})", trimmed));
            }
        }

        let sql = format!("ALTER TABLE {} ADD COLUMN {}", qualified, col_def);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!(
            "Added column {} on {}.{}",
            req.column.name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn drop_column(
        &self,
        req: &DropColumnRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.column_name, "Column name")?;

        let qualified = qualified_table(&req.schema, &req.table);
        let quoted_col = quote_ident(&req.column_name);
        // MySQL DROP COLUMN has no CASCADE keyword either — `req.cascade` is
        // ignored.
        let sql = format!("ALTER TABLE {} DROP COLUMN {}", qualified, quoted_col);

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &sql).await?;
        info!(
            "Dropped column {} from {}.{}",
            req.column_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn create_table(
        &self,
        req: &CreateTableRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.name, "Table name")?;

        if req.columns.is_empty() {
            return Err(AppError::Validation(
                "Table must have at least one column".into(),
            ));
        }

        for col in &req.columns {
            validate_identifier(&col.name, "Column name")?;
            if col.data_type.trim().is_empty() {
                return Err(AppError::Validation(format!(
                    "Column '{}' must have a non-empty data type",
                    col.name
                )));
            }
            validate_ddl_fragment(&col.data_type, "Data type")?;
            if let Some(default) = &col.default_value {
                validate_ddl_fragment(default, "DEFAULT value")?;
            }
        }

        if let Some(pk_cols) = &req.primary_key {
            for pk in pk_cols {
                validate_identifier(pk, "Primary key column name")?;
                if !req.columns.iter().any(|c| c.name == *pk) {
                    return Err(AppError::Validation(format!(
                        "Primary key column '{}' is not declared in the column list",
                        pk
                    )));
                }
            }
        }

        let qualified = qualified_table(&req.schema, &req.name);

        let mut col_defs: Vec<String> = Vec::with_capacity(req.columns.len() + 1);
        for col in &req.columns {
            let mut def = format!("{} {}", quote_ident(&col.name), col.data_type.trim());
            if col.is_identity {
                def.push_str(" AUTO_INCREMENT NOT NULL");
            } else {
                if !col.nullable {
                    def.push_str(" NOT NULL");
                }
                if let Some(default) = &col.default_value {
                    let trimmed = default.trim();
                    if !trimmed.is_empty() {
                        def.push_str(&format!(" DEFAULT {}", trimmed));
                    }
                }
            }
            // A MySQL column comment is inline in the column definition (PG
            // has a separate `COMMENT ON COLUMN` statement), so no separate
            // atomic chain is needed.
            if let Some(raw) = &col.comment {
                let trimmed = raw.trim();
                if !trimmed.is_empty() {
                    let escaped = escape_string_literal(trimmed);
                    def.push_str(&format!(" COMMENT '{}'", escaped));
                }
            }
            col_defs.push(def);
        }

        if let Some(pk_cols) = &req.primary_key {
            if !pk_cols.is_empty() {
                let quoted: Vec<String> = pk_cols.iter().map(|c| quote_ident(c)).collect();
                col_defs.push(format!("PRIMARY KEY ({})", quoted.join(", ")));
            }
        }

        // Engine/charset suffix is left to the server default (InnoDB /
        // utf8mb4 recommended) — users who want another engine use raw SQL.
        let mut create_sql = format!("CREATE TABLE {} ({})", qualified, col_defs.join(", "));

        // A table-level COMMENT can be inlined as a CREATE TABLE option —
        // `(cols) COMMENT = '…'`. Same effect as PG's separate
        // `COMMENT ON TABLE` statement.
        if let Some(raw) = &req.table_comment {
            let trimmed = raw.trim();
            if !trimmed.is_empty() {
                let escaped = escape_string_literal(trimmed);
                create_sql.push_str(&format!(" COMMENT = '{}'", escaped));
            }
        }

        if req.preview_only {
            return Ok(SchemaChangeResult { sql: create_sql });
        }

        let pool = self.active_pool().await?;
        run_in_tx(&pool, &create_sql).await?;
        info!("Created table {}.{}", req.schema, req.name);
        Ok(SchemaChangeResult { sql: create_sql })
    }

    pub async fn alter_table(
        &self,
        req: &AlterTableRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;

        if req.changes.is_empty() {
            return Err(AppError::Validation(
                "At least one column change is required".into(),
            ));
        }

        for change in &req.changes {
            match change {
                ColumnChange::Add {
                    name,
                    data_type,
                    default_value,
                    ..
                } => {
                    validate_identifier(name, "Column name")?;
                    validate_ddl_fragment(data_type, "Data type")?;
                    if let Some(default) = default_value {
                        validate_ddl_fragment(default, "DEFAULT value")?;
                    }
                }
                ColumnChange::Modify {
                    name,
                    new_data_type,
                    new_default_value,
                    using_expression,
                    ..
                } => {
                    validate_identifier(name, "Column name")?;
                    if new_data_type.is_none() && using_expression.is_some() {
                        return Err(AppError::Validation(
                            "USING expression requires a new data type (MySQL ignores USING — use raw SQL for casts)".into(),
                        ));
                    }
                    if let Some(dt) = new_data_type {
                        validate_ddl_fragment(dt, "Data type")?;
                    }
                    if let Some(default) = new_default_value {
                        validate_ddl_fragment(default, "DEFAULT value")?;
                    }
                }
                ColumnChange::Drop { name } => validate_identifier(name, "Column name")?,
            }
        }

        let qualified = qualified_table(&req.schema, &req.table);
        let mut parts: Vec<String> = Vec::new();

        for change in &req.changes {
            match change {
                ColumnChange::Add {
                    name,
                    data_type,
                    nullable,
                    default_value,
                } => {
                    let mut sql = format!("ADD COLUMN {} {}", quote_ident(name), data_type);
                    if !nullable {
                        sql.push_str(" NOT NULL");
                    }
                    if let Some(default) = default_value {
                        sql.push_str(&format!(" DEFAULT {}", default));
                    }
                    parts.push(sql);
                }
                ColumnChange::Modify {
                    name,
                    new_data_type,
                    new_nullable,
                    new_default_value,
                    using_expression: _,
                    // #1735 — MySQL has no ANSI `COMMENT ON`; a column comment
                    // rides inside the column definition, so changing it means
                    // re-emitting the FULL `MODIFY COLUMN` definition (type,
                    // nullability, default, charset, auto_increment) — lossy
                    // whenever an attribute is absent from the payload. Not
                    // wired here; the UI gates it off via
                    // `ddl.editColumnComment: false`, so no comment reaches
                    // this arm.
                    new_comment: _,
                } => {
                    // MySQL's modify column cannot send type/nullable/default
                    // as separate clauses the way PG does — it rewrites the
                    // whole column definition as
                    // `MODIFY COLUMN col <type> [NOT NULL] [DEFAULT v]`. When
                    // new_data_type is None there is no marker such as
                    // `'KEEP TYPE'` to fall back on, so this rejects
                    // explicitly — the frontend caller always sends the type
                    // along.
                    let quoted_name = quote_ident(name);
                    let Some(dt) = new_data_type else {
                        return Err(AppError::Validation(format!(
                            "MySQL MODIFY COLUMN requires a data type for '{}'",
                            name
                        )));
                    };
                    let mut sql = format!("MODIFY COLUMN {} {}", quoted_name, dt);
                    if let Some(nullable) = new_nullable {
                        sql.push_str(if *nullable { " NULL" } else { " NOT NULL" });
                    }
                    if let Some(default) = new_default_value {
                        sql.push_str(&format!(" DEFAULT {}", default));
                    }
                    parts.push(sql);
                }
                ColumnChange::Drop { name } => {
                    parts.push(format!("DROP COLUMN {}", quote_ident(name)));
                }
            }
        }

        let sql = format!("ALTER TABLE {} {}", qualified, parts.join(", "));

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!("Altered table {}.{}", req.schema, req.table);
        Ok(SchemaChangeResult { sql })
    }

    pub async fn create_index(
        &self,
        req: &CreateIndexRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.index_name, "Index name")?;

        if req.columns.is_empty() {
            return Err(AppError::Validation(
                "At least one column is required for an index".into(),
            ));
        }
        for col in &req.columns {
            validate_identifier(col, "Index column name")?;
        }

        let index_type_lower = req.index_type.to_lowercase();
        if !MYSQL_INDEX_TYPES.contains(&index_type_lower.as_str()) {
            return Err(AppError::Validation(format!(
                "Index type must be one of: {}",
                MYSQL_INDEX_TYPES.join(", ")
            )));
        }

        let qualified = qualified_table(&req.schema, &req.table);
        let columns: Vec<String> = req.columns.iter().map(|c| quote_ident(c)).collect();

        let unique = if req.is_unique { "UNIQUE " } else { "" };
        let sql = format!(
            "CREATE {}INDEX {} USING {} ON {} ({})",
            unique,
            quote_ident(&req.index_name),
            index_type_lower.to_uppercase(),
            qualified,
            columns.join(", ")
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!(
            "Created index {} on {}.{}",
            req.index_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn drop_index(&self, req: &DropIndexRequest) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.index_name, "Index name")?;
        // MySQL DROP INDEX needs `ON <table>`. A PG caller may omit the
        // table, but this adapter rejects a schema-only request with an
        // explicit validation error instead of silently swallowing a missing
        // frontend payload.
        if req.table.trim().is_empty() {
            return Err(AppError::Validation(
                "MySQL DROP INDEX requires a table — request.table must not be empty".into(),
            ));
        }
        validate_identifier(&req.table, "Table name")?;
        let qualified = qualified_table(&req.schema, &req.table);
        // MySQL supports IF EXISTS from 8.0.13+. Older servers surface a
        // syntax error — turning the option toggle OFF in the frontend is
        // recommended there.
        let if_exists = if req.if_exists { "IF EXISTS " } else { "" };
        let sql = format!(
            "DROP INDEX {}{} ON {}",
            if_exists,
            quote_ident(&req.index_name),
            qualified
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!("Dropped index {}.{}", req.schema, req.index_name);
        Ok(SchemaChangeResult { sql })
    }

    pub async fn add_constraint(
        &self,
        req: &AddConstraintRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.constraint_name, "Constraint name")?;

        let qualified = qualified_table(&req.schema, &req.table);
        let constraint_name = quote_ident(&req.constraint_name);

        let constraint_sql = match &req.definition {
            ConstraintDefinition::PrimaryKey { columns } => {
                if columns.is_empty() {
                    return Err(AppError::Validation(
                        "Primary key requires at least one column".into(),
                    ));
                }
                for col in columns {
                    validate_identifier(col, "Primary key column name")?;
                }
                let cols: Vec<String> = columns.iter().map(|c| quote_ident(c)).collect();
                // A MySQL PRIMARY KEY cannot be a named constraint — the
                // name is ignored. `ADD CONSTRAINT name PRIMARY KEY` parses,
                // but the name part is silently dropped. Emission keeps the
                // same form.
                format!("PRIMARY KEY ({})", cols.join(", "))
            }
            ConstraintDefinition::ForeignKey {
                columns,
                reference_table,
                reference_columns,
                on_delete,
                on_update,
            } => {
                if columns.is_empty() {
                    return Err(AppError::Validation(
                        "Foreign key requires at least one column".into(),
                    ));
                }
                for col in columns {
                    validate_identifier(col, "Foreign key column name")?;
                }
                validate_identifier(reference_table, "Foreign key reference table name")?;
                for col in reference_columns {
                    validate_identifier(col, "Foreign key reference column name")?;
                }
                let cols: Vec<String> = columns.iter().map(|c| quote_ident(c)).collect();
                let ref_cols: Vec<String> =
                    reference_columns.iter().map(|c| quote_ident(c)).collect();
                let on_delete_clause =
                    format_referential_action_clause(on_delete.as_deref(), "ON DELETE")?;
                let on_update_clause =
                    format_referential_action_clause(on_update.as_deref(), "ON UPDATE")?;
                // A MySQL FK takes only reference_table; the schema is
                // implicit (or written as `db.table`). This emitter does not
                // qualify the schema freely and emits table-only like PG —
                // cross-schema FKs are better written in raw SQL.
                format!(
                    "FOREIGN KEY ({}) REFERENCES {} ({}){}{}",
                    cols.join(", "),
                    quote_ident(reference_table),
                    ref_cols.join(", "),
                    on_delete_clause,
                    on_update_clause,
                )
            }
            ConstraintDefinition::Unique { columns } => {
                if columns.is_empty() {
                    return Err(AppError::Validation(
                        "Unique constraint requires at least one column".into(),
                    ));
                }
                for col in columns {
                    validate_identifier(col, "Unique constraint column name")?;
                }
                let cols: Vec<String> = columns.iter().map(|c| quote_ident(c)).collect();
                format!("UNIQUE ({})", cols.join(", "))
            }
            ConstraintDefinition::Check { expression } => {
                let expression = expression.trim();
                if expression.is_empty() {
                    return Err(AppError::Validation(
                        "Check constraint expression must not be empty".into(),
                    ));
                }
                validate_ddl_fragment(expression, "Check expression")?;
                // CHECK is enforced from MySQL 8.0.16+. Older servers parse
                // the SQL but ignore it — a compatibility issue the server
                // surfaces.
                format!("CHECK ({})", expression)
            }
        };

        let sql = format!(
            "ALTER TABLE {} ADD CONSTRAINT {} {}",
            qualified, constraint_name, constraint_sql
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!(
            "Added constraint {} on {}.{}",
            req.constraint_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }

    pub async fn drop_constraint(
        &self,
        req: &DropConstraintRequest,
    ) -> Result<SchemaChangeResult, AppError> {
        validate_identifier(&req.schema, "Schema name")?;
        validate_identifier(&req.table, "Table name")?;
        validate_identifier(&req.constraint_name, "Constraint name")?;

        let qualified = qualified_table(&req.schema, &req.table);
        // Uses MySQL 8.0.19+'s unified `DROP CONSTRAINT name` — it handles
        // CHECK / UNIQUE / FK. For a PK, the unified syntax resolves the
        // explicit `DROP PRIMARY KEY` through its lookup table.
        let sql = format!(
            "ALTER TABLE {} DROP CONSTRAINT {}",
            qualified,
            quote_ident(&req.constraint_name)
        );

        if req.preview_only {
            return Ok(SchemaChangeResult { sql });
        }

        let pool = self.active_pool().await?;
        sqlx::query(&sql)
            .execute(&pool)
            .await
            .map_err(|e| AppError::Database(e.to_string()))?;
        info!(
            "Dropped constraint {} from {}.{}",
            req.constraint_name, req.schema, req.table
        );
        Ok(SchemaChangeResult { sql })
    }
}

#[cfg(test)]
mod tests {
    //! Reason (2026-05-13): SQL emission is pure (it builds without a pool),
    //! so the preview_only=true path guards byte-equivalent regressions.
    //! Identifier validation and the MySQL-specific emission differences
    //! (RENAME TABLE, AUTO_INCREMENT, MODIFY COLUMN, DROP INDEX … ON …) are
    //! guarded first because a regression there breaks the user-facing
    //! frontend preview.
    use super::*;
    use crate::models::{
        AddColumnRequest, AddConstraintRequest, AlterTableRequest, ColumnChange, ColumnDefinition,
        ConstraintDefinition, CreateIndexRequest, CreateTableRequest, DropColumnRequest,
        DropConstraintRequest, DropIndexRequest, DropTableRequest, RenameTableRequest,
    };

    fn drop_req(schema: &str, table: &str) -> DropTableRequest {
        DropTableRequest {
            connection_id: "c".into(),
            schema: schema.into(),
            table: table.into(),
            cascade: false,
            preview_only: true,
            expected_database: None,
        }
    }

    fn rename_req(schema: &str, table: &str, new_name: &str) -> RenameTableRequest {
        RenameTableRequest {
            connection_id: "c".into(),
            schema: schema.into(),
            table: table.into(),
            new_name: new_name.into(),
            preview_only: true,
            expected_database: None,
        }
    }

    #[test]
    fn validate_identifier_rejects_empty_and_special_chars() {
        assert!(validate_identifier("", "Col").is_err());
        assert!(validate_identifier("   ", "Col").is_err());
        assert!(validate_identifier("1abc", "Col").is_err());
        assert!(validate_identifier("a-b", "Col").is_err());
        assert!(validate_identifier("a b", "Col").is_err());
        assert!(validate_identifier("a`b", "Col").is_err());
        assert!(validate_identifier("a\"b", "Col").is_err());
    }

    #[test]
    fn validate_identifier_accepts_ascii_underscore_alnum() {
        assert!(validate_identifier("users", "T").is_ok());
        assert!(validate_identifier("_priv", "T").is_ok());
        assert!(validate_identifier("col_1", "T").is_ok());
    }

    #[test]
    fn validate_identifier_enforces_64_byte_limit() {
        // 65-byte name — over the MySQL limit.
        let long = "a".repeat(65);
        let err = validate_identifier(&long, "Col").unwrap_err();
        assert!(format!("{err}").contains("64"));
        // Exactly 64 bytes passes.
        let ok = "a".repeat(64);
        assert!(validate_identifier(&ok, "Col").is_ok());
    }

    #[test]
    fn quote_ident_doubles_backticks() {
        assert_eq!(quote_ident("users"), "`users`");
        assert_eq!(quote_ident("we`ird"), "`we``ird`");
    }

    #[tokio::test]
    async fn drop_table_preview_emits_simple_form() {
        let a = MysqlAdapter::new();
        let req = drop_req("app", "users");
        let r = a.drop_table(&req).await.unwrap();
        assert_eq!(r.sql, "DROP TABLE `app`.`users`");
    }

    #[tokio::test]
    async fn drop_table_preview_ignores_cascade_flag() {
        let a = MysqlAdapter::new();
        let mut req = drop_req("app", "users");
        req.cascade = true;
        let r = a.drop_table(&req).await.unwrap();
        // MySQL has no CASCADE keyword — emission is unchanged.
        assert_eq!(r.sql, "DROP TABLE `app`.`users`");
    }

    #[tokio::test]
    async fn rename_table_preview_uses_rename_table_syntax() {
        let a = MysqlAdapter::new();
        let req = rename_req("app", "users", "people");
        let r = a.rename_table(&req).await.unwrap();
        assert_eq!(r.sql, "RENAME TABLE `app`.`users` TO `app`.`people`");
    }

    #[tokio::test]
    async fn add_column_preview_emits_identity_as_auto_increment() {
        let a = MysqlAdapter::new();
        let req = AddColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column: ColumnDefinition {
                name: "id".into(),
                data_type: "BIGINT".into(),
                nullable: true,
                default_value: None,
                is_identity: true,
                comment: None,
            },
            check_expression: None,
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_column(&req).await.unwrap();
        assert!(
            r.sql.contains("AUTO_INCREMENT NOT NULL"),
            "expected AUTO_INCREMENT NOT NULL emission: {}",
            r.sql
        );
        assert!(r.sql.contains("ALTER TABLE `app`.`users`"));
    }

    #[tokio::test]
    async fn add_column_preview_emits_check_clause() {
        let a = MysqlAdapter::new();
        let req = AddColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column: ColumnDefinition {
                name: "age".into(),
                data_type: "INT".into(),
                nullable: false,
                default_value: None,
                is_identity: false,
                comment: None,
            },
            check_expression: Some("age >= 0".into()),
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_column(&req).await.unwrap();
        assert!(
            r.sql.ends_with("CHECK (age >= 0)"),
            "expected trailing CHECK: {}",
            r.sql
        );
    }

    #[tokio::test]
    async fn drop_column_preview_no_cascade_keyword() {
        let a = MysqlAdapter::new();
        let req = DropColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column_name: "deprecated".into(),
            cascade: true,
            preview_only: true,
            expected_database: None,
        };
        let r = a.drop_column(&req).await.unwrap();
        // Even with cascade=true, MySQL has no CASCADE keyword.
        assert_eq!(r.sql, "ALTER TABLE `app`.`users` DROP COLUMN `deprecated`");
    }

    #[tokio::test]
    async fn create_table_preview_emits_columns_pk_and_comments() {
        let a = MysqlAdapter::new();
        let req = CreateTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            name: "users".into(),
            columns: vec![
                ColumnDefinition {
                    name: "id".into(),
                    data_type: "BIGINT".into(),
                    nullable: false,
                    default_value: None,
                    is_identity: true,
                    comment: Some("PK".into()),
                },
                ColumnDefinition {
                    name: "name".into(),
                    data_type: "VARCHAR(120)".into(),
                    nullable: false,
                    default_value: Some("'anon'".into()),
                    is_identity: false,
                    comment: None,
                },
            ],
            primary_key: Some(vec!["id".into()]),
            table_comment: Some("user records".into()),
            preview_only: true,
            expected_database: None,
        };
        let r = a.create_table(&req).await.unwrap();
        assert!(r.sql.starts_with("CREATE TABLE `app`.`users` ("));
        assert!(r
            .sql
            .contains("`id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'PK'"));
        assert!(r
            .sql
            .contains("`name` VARCHAR(120) NOT NULL DEFAULT 'anon'"));
        assert!(r.sql.contains("PRIMARY KEY (`id`)"));
        assert!(r.sql.ends_with("COMMENT = 'user records'"));
    }

    #[test]
    fn escape_string_literal_doubles_backslash_and_quote() {
        // #1109: in the default SQL mode both `\` and `'` are escape
        // characters, so both get doubled. Without handling the backslash
        // first, it re-escapes the quote written as `''` and the value
        // escapes the literal.
        assert_eq!(escape_string_literal("C:\\data\\"), "C:\\\\data\\\\");
        assert_eq!(escape_string_literal("x\\'; DROP"), "x\\\\''; DROP");
        assert_eq!(escape_string_literal("plain"), "plain");
        assert_eq!(escape_string_literal("O'Brien"), "O''Brien");
    }

    #[tokio::test]
    async fn column_comment_escapes_backslash_so_literal_stays_closed() {
        // #1109 regression: a `C:\data\` COMMENT escaped the closing quote
        // and broke the DDL. Doubling the backslash must close the literal
        // properly.
        let a = MysqlAdapter::new();
        let req = AddColumnRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            column: ColumnDefinition {
                name: "path".into(),
                data_type: "VARCHAR(255)".into(),
                nullable: true,
                default_value: None,
                is_identity: false,
                comment: Some("C:\\data\\".into()),
            },
            check_expression: None,
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_column(&req).await.unwrap();
        // The closing quote is an unescaped single quote (preceded by `\\`).
        assert!(
            r.sql.ends_with(" COMMENT 'C:\\\\data\\\\'"),
            "backslash 미escape 로 리터럴 파손: {}",
            r.sql
        );
    }

    #[tokio::test]
    async fn comment_backslash_quote_cannot_escape_literal() {
        // #1109, security side: `x\'; DROP` used the backslash to defeat the
        // `''` doubling and escape the literal. Doubling the backslash makes
        // that impossible.
        let a = MysqlAdapter::new();
        let req = CreateTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            name: "t".into(),
            columns: vec![ColumnDefinition {
                name: "c".into(),
                data_type: "INT".into(),
                nullable: true,
                default_value: None,
                is_identity: false,
                comment: None,
            }],
            primary_key: None,
            table_comment: Some("x\\'; DROP".into()),
            preview_only: true,
            expected_database: None,
        };
        let r = a.create_table(&req).await.unwrap();
        assert!(
            r.sql.ends_with(" COMMENT = 'x\\\\''; DROP'"),
            "backslash 로 quote escape 를 무력화하는 탈출 여지: {}",
            r.sql
        );
    }

    #[tokio::test]
    async fn alter_table_preview_modify_requires_data_type() {
        let a = MysqlAdapter::new();
        let req = AlterTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            changes: vec![ColumnChange::Modify {
                name: "age".into(),
                new_data_type: None,
                new_nullable: Some(true),
                new_default_value: None,
                using_expression: None,
                new_comment: None,
            }],
            preview_only: true,
            expected_database: None,
        };
        let err = a.alter_table(&req).await.unwrap_err();
        assert!(format!("{err}").contains("data type"));
    }

    #[tokio::test]
    async fn alter_table_preview_modify_emits_modify_column() {
        let a = MysqlAdapter::new();
        let req = AlterTableRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            changes: vec![ColumnChange::Modify {
                name: "age".into(),
                new_data_type: Some("BIGINT".into()),
                new_nullable: Some(false),
                new_default_value: Some("0".into()),
                using_expression: None,
                new_comment: None,
            }],
            preview_only: true,
            expected_database: None,
        };
        let r = a.alter_table(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`users` MODIFY COLUMN `age` BIGINT NOT NULL DEFAULT 0"
        );
    }

    #[tokio::test]
    async fn create_index_preview_btree_unique() {
        let a = MysqlAdapter::new();
        let req = CreateIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            index_name: "idx_users_email".into(),
            columns: vec!["email".into()],
            is_unique: true,
            index_type: "btree".into(),
            preview_only: true,
            expected_database: None,
        };
        let r = a.create_index(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "CREATE UNIQUE INDEX `idx_users_email` USING BTREE ON `app`.`users` (`email`)"
        );
    }

    #[tokio::test]
    async fn create_index_rejects_unknown_type() {
        let a = MysqlAdapter::new();
        let req = CreateIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            index_name: "i".into(),
            columns: vec!["email".into()],
            is_unique: false,
            index_type: "gin".into(),
            preview_only: true,
            expected_database: None,
        };
        let err = a.create_index(&req).await.unwrap_err();
        assert!(format!("{err}").to_lowercase().contains("btree"));
    }

    #[tokio::test]
    async fn drop_index_preview_emits_on_table() {
        let a = MysqlAdapter::new();
        let req = DropIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            index_name: "idx_x".into(),
            if_exists: true,
            preview_only: true,
            expected_database: None,
        };
        let r = a.drop_index(&req).await.unwrap();
        assert_eq!(r.sql, "DROP INDEX IF EXISTS `idx_x` ON `app`.`users`");
    }

    #[tokio::test]
    async fn drop_index_requires_table() {
        let a = MysqlAdapter::new();
        let req = DropIndexRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "".into(),
            index_name: "idx_x".into(),
            if_exists: false,
            preview_only: true,
            expected_database: None,
        };
        let err = a.drop_index(&req).await.unwrap_err();
        assert!(format!("{err}").contains("table"));
    }

    #[tokio::test]
    async fn add_constraint_check_preview() {
        let a = MysqlAdapter::new();
        let req = AddConstraintRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "users".into(),
            constraint_name: "chk_age".into(),
            definition: ConstraintDefinition::Check {
                expression: "age >= 0".into(),
            },
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_constraint(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`users` ADD CONSTRAINT `chk_age` CHECK (age >= 0)"
        );
    }

    #[tokio::test]
    async fn add_constraint_fk_with_actions() {
        let a = MysqlAdapter::new();
        let req = AddConstraintRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "orders".into(),
            constraint_name: "fk_user".into(),
            definition: ConstraintDefinition::ForeignKey {
                columns: vec!["user_id".into()],
                reference_table: "users".into(),
                reference_columns: vec!["id".into()],
                on_delete: Some("CASCADE".into()),
                on_update: Some("RESTRICT".into()),
            },
            preview_only: true,
            expected_database: None,
        };
        let r = a.add_constraint(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`orders` ADD CONSTRAINT `fk_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT"
        );
    }

    #[tokio::test]
    async fn drop_constraint_preview_uses_unified_syntax() {
        let a = MysqlAdapter::new();
        let req = DropConstraintRequest {
            connection_id: "c".into(),
            schema: "app".into(),
            table: "orders".into(),
            constraint_name: "fk_user".into(),
            preview_only: true,
            expected_database: None,
        };
        let r = a.drop_constraint(&req).await.unwrap();
        assert_eq!(
            r.sql,
            "ALTER TABLE `app`.`orders` DROP CONSTRAINT `fk_user`"
        );
    }
}
