// #1805 — WASM-backed Redis/Valkey completion vocabulary.
//
// The vocabulary SOT is the `redis-command-core` Rust crate
// (`src-tauri/redis-command-core`); this facade lazy-loads the wasm-pack
// module built from it (`src/lib/redis/wasm/`, artifacts tracked in git).
// Callers of `createRedisCommandCompletionSource` expect a *sync* signature,
// so the facade follows the mongosh parser pattern: `main.tsx` preloads the
// module during boot (fire-and-forget), and until it lands the vocabulary
// reads as `null` — the completion source then suggests nothing instead of
// throwing or going async.

export type RedisCommandCompletionEffect =
  | "read"
  | "write"
  | "ttl"
  | "stream"
  | "destructive";

/**
 * One row of the vocabulary as serialized by `redis-command-core`.
 * `probe` is omitted there (`#[serde(skip)]`) — it exists only for the
 * native drift guard in `table-view-core`.
 */
export interface RedisCommandCoreRow {
  readonly name: string;
  readonly effect: RedisCommandCompletionEffect;
  readonly arity: string;
  readonly arguments: readonly string[];
  readonly snippet: string;
  readonly summary: string;
  readonly keyArgument: "none" | "any" | "variadic-any" | "key-types";
  readonly keyTypes: readonly string[];
  readonly valkeyProven: boolean;
}

// ---------------------------------------------------------------------------
// WASM module shape — generated by `wasm-pack build --target web`.
// ---------------------------------------------------------------------------

interface RedisCommandWasmModule {
  default: (input?: unknown) => Promise<unknown>;
  initSync: (input: { module: BufferSource | WebAssembly.Module }) => unknown;
  redis_command_completion_vocabulary: () => unknown;
}

let wasmModule: RedisCommandWasmModule | null = null;
let modulePromise: Promise<RedisCommandWasmModule> | null = null;

/**
 * Public eager-init entry. Memoized. Optional `precompiledBytes` lets the
 * test-setup pass an on-disk byte buffer; under jsdom the default `fetch()`
 * codepath would fail.
 */
export function initRedisCommandWasm(
  precompiledBytes?: BufferSource | WebAssembly.Module,
): Promise<void> {
  if (modulePromise === null) {
    modulePromise = (async () => {
      // Dynamic import — Vite tree-splits the wasm-pack glue into its own
      // chunk so it does not land in the main entry bundle.
      const mod = (await import(
        "./wasm/redis_command_core.js"
      )) as unknown as RedisCommandWasmModule;
      if (precompiledBytes !== undefined) {
        mod.initSync({ module: precompiledBytes });
      } else {
        // `default` is the wasm-pack `--target web` init function; called
        // with no args it locates the sibling `.wasm` via
        // `new URL("...", import.meta.url)`.
        await mod.default();
      }
      wasmModule = mod;
      return mod;
    })();
  }
  return modulePromise.then(() => undefined);
}

/**
 * The vocabulary rows in Rust table order, or `null` while the WASM module
 * has not loaded (or its payload failed validation) — callers treat `null`
 * as "no suggestions yet".
 */
export function getRedisCommandRows(): readonly RedisCommandCoreRow[] | null {
  if (wasmModule === null) return null;
  return parseRows(wasmModule.redis_command_completion_vocabulary());
}

function parseRows(value: unknown): readonly RedisCommandCoreRow[] | null {
  if (!Array.isArray(value)) return null;
  // All-or-nothing: a partially valid payload means a serialization bug in
  // the bridge, and a silently shortened vocabulary is harder to notice than
  // an empty one.
  if (!value.every(isRow)) return null;
  return value;
}

function isRow(value: unknown): value is RedisCommandCoreRow {
  if (typeof value !== "object" || value === null) return false;
  const row = value as Record<string, unknown>;
  return (
    typeof row.name === "string" &&
    typeof row.effect === "string" &&
    typeof row.arity === "string" &&
    Array.isArray(row.arguments) &&
    typeof row.snippet === "string" &&
    typeof row.summary === "string" &&
    typeof row.keyArgument === "string" &&
    Array.isArray(row.keyTypes) &&
    typeof row.valkeyProven === "boolean"
  );
}

/**
 * Test-only escape hatch — resets the memoized module promise so a spec can
 * exercise the not-yet-loaded path. Not part of the public surface.
 */
export function __resetRedisCommandWasmModuleForTests(): void {
  modulePromise = null;
  wasmModule = null;
}
